// Code generated by forge const -- DO NOT EDIT.
//
//   source: grammar_test.sdl

export type UID = readonly [bigint, bigint];

export interface TagName {
    readonly id:      UID;
    readonly canonic: string;
}

export const Name = {
    // ─── This is a big fancy comment, ───────────────────────────────
    AppTag             : { id: [0x9FC2012FD63F847An, 0x51AA55A31D90CD25n], canonic: "app" },        // 4ZS80KZPJZHJX53BKPNDFT1M95

    AppState           : { id: [0xFAA5BBA978628672n, 0x22BC2C65BFDD460Cn], canonic: "app.state" },  // 7UNQXUKY32HTT25G1DDQZXUJHD

    // ─── This is a very descriptive comment ─────────────────────────
    // that spans multiple lines to exercise
    // the multi-line doc-comment code path.
    SessionAttr        : { id: [0x5948CA6969CBDF2Fn, 0x01C92A44FA60AB24n], canonic: "session" },                          // 2T9356KUFCVWRH3K9B8MX61BT4

    LoginID            : { id: [0x761CD041F19A871En, 0x588D714F3B7C0369n], canonic: "session.login" },                    // 3Q3M843WDUHWG5J3CJ9WXRS0V9
    SessionTag         : { id: [0xCCE00314A1263502n, 0x7A38CD68C10DC759n], canonic: "session.tag" },                      // 6DW01J98966N17NF6EE30HVJUT

    LaunchWeb          : { id: [0x7900A4A514A3C61Bn, 0x69753310BD7BA8BBn], canonic: "session.tag.www" },                  // 3T02KBB553SSEQKX9M22YRRB5V
    ReallySuperLongName: { id: [0xDB93E07BBD0F0827n, 0xCA42D43B008D32CCn], canonic: "session.tag.reallysuperlongname" },  // 6VKGH7RG8G10MWNHQN7D08UDQD
} satisfies Record<string, TagName>;

export const ID = {
    SiteDownloads: { id: [0xB30A33823CA36F9En, 0x379DE2617633209Cn], canonic: "http://acme.com/downloads/" },  // 5M18TS4G53EYG3G7G2D5V3684W
    TestNet      : { id: [0x46407EE5F0A5436Fn, 0xDC383E0601E3386An], canonic: "your-scheme://server.com:23382/path" },  // 2681ZFCW558ERXSF1Y0S0Y6F3B
    BestShow     : { id: [0x9A99BA231EF8C148n, 0x63D4A9B0DE7D7F41n], canonic: "fraggle.rock" },  // 4UM6X267RSS5467P59Q3G7UZU1
} satisfies Record<string, TagName>;

// Bootstrapping node ID
export const TestingID:      UID = [0x7n, 0x8n];
// UUID literals — every form accepted by gofrs/uuid.FromString is normalized
// to the same {hi, lo} hex-pair output.  Same UUID, six syntactic spellings:
export const UUID_Canonical: UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
export const UUID_Uppercase: UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
export const UUID_Compact:   UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
export const UUID_Braced:    UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
export const UUID_URN:       UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
export const UUID_MixedCase: UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
// Sentinel UUIDs that downstream callers occasionally need to express.
export const UUID_Nil:       UID = [0x0000000000000000n, 0x0000000000000000n];
export const UUID_Max:       UID = [0xFFFFFFFFFFFFFFFFn, 0xFFFFFFFFFFFFFFFFn];
// A distinct UUID, to confirm the parser disambiguates between sources.
export const HiMom:          UID = [0x6BA7B8109DAD11D1n, 0x80B400C04FD430C8n];

// Scalar string constants
export const MaxFraction: bigint = 1000000000n;
export const HexConst:    bigint = 0xFFFFFFFFFFFFFFF0n;
export const Pi:          number = 3.14159265358979;
export const SmallPi:     number = 3.14;
export const TwoPi:       number = 3.14159265358979;

export const SomeFiles = {
    WindowsHosts: "C:\\Windows\\System32\\drivers\\etc\\hosts",
    UnixHosts:    "/etc/hosts",
    MacHosts:     "/private/etc/hosts",
} as const;

export const Moar = {
    MaxFraction: 1000000000n,
    TwoPi:       3.14159265358979,
    Striiing:    "hello sailor",
} as const;

export const Glyph = {
    WebLink:     "asset:glyph/web.link",
    DefaultNode: "asset:glyph/default.node",
} as const;

export const Herro = {
    WebLink:     "fooled you",
    DefaultNode: "default this",
} as const;

// ─── Mixed-type group: scalars emit as const, UIDs as var (Go forbids struct ───
// literals in const blocks).  Flat-prefixed by the group name — access is
// `std.SessionContextID` + `std.SessionLaunchPath`.
export const Session = {
    ContextID:  [0x0n, 0x777n],
    LaunchPath: "/session/start",
} as const;
