// Code generated by forge const -- DO NOT EDIT.
//
//   source: grammar_test.sdl

package std

import "github.com/art-media-platform/amp.SDK/stdlib/tag"

var Name = struct {
	AppTag              tag.Name
	AppState            tag.Name
	SessionAttr         tag.Name
	LoginID             tag.Name
	SessionTag          tag.Name
	LaunchWeb           tag.Name
	ReallySuperLongName tag.Name
}{
	// ─── This is a big fancy comment, ───────────────────────────────
	AppTag: tag.Name{ID: tag.UID{0x9FC2012FD63F847A, 0x51AA55A31D90CD25}, Text: "app"}, // 4zs80k-zpjzh-jx53b-kpndf-t1m95

	AppState: tag.Name{ID: tag.UID{0xFAA5BBA978628672, 0x22BC2C65BFDD460C}, Text: "app.state"}, // 7unqxu-ky32h-tt25g-1ddqz-xujhd

	// ─── This is a very descriptive comment ─────────────────────────
	// that spans multiple lines to exercise
	// the multi-line doc-comment code path.
	SessionAttr: tag.Name{ID: tag.UID{0x5948CA6969CBDF2F, 0x01C92A44FA60AB24}, Text: "session"}, // 2t9356-kufcv-wrh3k-9b8mx-61bt4

	LoginID:    tag.Name{ID: tag.UID{0x761CD041F19A871E, 0x588D714F3B7C0369}, Text: "session.Login"}, // 3q3m84-3wduh-wg5j3-cj9wx-rs0v9
	SessionTag: tag.Name{ID: tag.UID{0xCCE00314A1263502, 0x7A38CD68C10DC759}, Text: "session.Tag"},   // 6dw01j-98966-n17nf-6ee30-hvjut

	LaunchWeb:           tag.Name{ID: tag.UID{0x7900A4A514A3C61B, 0x69753310BD7BA8BB}, Text: "session.Tag.www"},                 // 3t02kb-b553s-seqkx-9m22y-rrb5v
	ReallySuperLongName: tag.Name{ID: tag.UID{0xDB93E07BBD0F0827, 0xCA42D43B008D32CC}, Text: "session.Tag.ReallySuperLongName"}, // 6vkgh7-rg8g1-0mwnh-qn7d0-8udqd
}

var ID = struct {
	SiteDownloads tag.Name
	TestNet       tag.Name
	BestShow      tag.Name
}{
	SiteDownloads: tag.Name{ID: tag.UID{0xB30A33823CA36F9E, 0x379DE2617633209C}, Text: "http://acme.com/downloads/"},          // 5m18ts-4g53e-yg3g7-g2d5v-3684w
	TestNet:       tag.Name{ID: tag.UID{0x46407EE5F0A5436F, 0xDC383E0601E3386A}, Text: "your-scheme://server.com:23382/path"}, // 2681zf-cw558-erxsf-1y0s0-y6f3b
	BestShow:      tag.Name{ID: tag.UID{0x9A99BA231EF8C148, 0x63D4A9B0DE7D7F41}, Text: "Fraggle.Rock"},                        // 4um6x2-67rss-5467p-59q3g-7uzu1
}

var (
	// Bootstrapping node ID
	TestingID = tag.UID{0x7, 0x8}
	// UUID literals — every form accepted by gofrs/uuid.FromString is normalized
	// to the same {hi, lo} hex-pair output.  Same UUID, six syntactic spellings:
	UUID_Canonical = tag.UID{0x550E8400E29B41D4, 0xA716446655440000}
	UUID_Uppercase = tag.UID{0x550E8400E29B41D4, 0xA716446655440000}
	UUID_Compact   = tag.UID{0x550E8400E29B41D4, 0xA716446655440000}
	UUID_Braced    = tag.UID{0x550E8400E29B41D4, 0xA716446655440000}
	UUID_URN       = tag.UID{0x550E8400E29B41D4, 0xA716446655440000}
	UUID_MixedCase = tag.UID{0x550E8400E29B41D4, 0xA716446655440000}
	// Sentinel UUIDs that downstream callers occasionally need to express.
	UUID_Nil = tag.UID{0x0000000000000000, 0x0000000000000000}
	UUID_Max = tag.UID{0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF}
	// A distinct UUID, to confirm the parser disambiguates between sources.
	HiMom = tag.UID{0x6BA7B8109DAD11D1, 0x80B400C04FD430C8}
)

const (
	// Scalar string constants
	MaxFraction = uint64(1000000000)
	HexConst    = uint64(0xFFFFFFFFFFFFFFF0)
	Pi          = 3.14159265358979
	SmallPi     = float32(3.14)
	TwoPi       = 3.14159265358979
	WholeRate   = 1.0
	TinyStep    = 1e-09
	WholeGain   = float32(2)
)

const (
	SomeFilesWindowsHosts = "C:\\Windows\\System32\\drivers\\etc\\hosts"
	SomeFilesUnixHosts    = "/etc/hosts"
	SomeFilesMacHosts     = "/private/etc/hosts"
)

const (
	MoarMaxFraction = uint64(1000000000)
	MoarTwoPi       = 3.14159265358979
	MoarStriiing    = "hello sailor"
)

const (
	GlyphWebLink     = "asset:glyph/web.link"
	GlyphDefaultNode = "asset:glyph/default.node"
)

const (
	HerroWebLink     = "fooled you"
	HerroDefaultNode = "default this"
)

// ─── Mixed-type group: scalars emit as const, UIDs as var (Go forbids struct ───
// literals in const blocks).  Flat-prefixed by the group name — access is
// `std.SessionContextID` + `std.SessionLaunchPath`.
const (
	SessionLaunchPath = "/session/start"
)

var (
	SessionContextID = tag.UID{0x0, 0x777}
)
