# Code generated by forge const -- DO NOT EDIT.
#
#   source: grammar_test.sdl

from typing import NamedTuple

UID = tuple[int, int]


class TagName(NamedTuple):
    id:   UID
    text: str


class Name:
    # ─── This is a big fancy comment, ───────────────────────────────
    AppTag              = TagName((0x9FC2012FD63F847A, 0x51AA55A31D90CD25), "app")        # 4zs-80kzpjzhjx-53bkpndft1-m95

    AppState            = TagName((0xFAA5BBA978628672, 0x22BC2C65BFDD460C), "app.state")  # 7un-qxuky32htt-25g1ddqzxu-jhd

    # ─── This is a very descriptive comment ─────────────────────────
    # that spans multiple lines to exercise
    # the multi-line doc-comment code path.
    SessionAttr         = TagName((0x5948CA6969CBDF2F, 0x01C92A44FA60AB24), "session")                          # 2t9-356kufcvwr-h3k9b8mx61-bt4

    LoginID             = TagName((0x761CD041F19A871E, 0x588D714F3B7C0369), "session.Login")                    # 3q3-m843wduhwg-5j3cj9wxrs-0v9
    SessionTag          = TagName((0xCCE00314A1263502, 0x7A38CD68C10DC759), "session.Tag")                      # 6dw-01j98966n1-7nf6ee30hv-jut

    LaunchWeb           = TagName((0x7900A4A514A3C61B, 0x69753310BD7BA8BB), "session.Tag.www")                  # 3t0-2kbb553sse-qkx9m22yrr-b5v
    ReallySuperLongName = TagName((0xDB93E07BBD0F0827, 0xCA42D43B008D32CC), "session.Tag.ReallySuperLongName")  # 6vk-gh7rg8g10m-wnhqn7d08u-dqd


class Attr:
    ItemAttr               = TagName((0xE8D8BECA5B3BBEB3, 0x1308458DB27C3504), "item")                   # 78v-2zdnqtvrut-j6225jqt7s-e84

    ItemLabels             = TagName((0x89DC7C30D083C0B7, 0xCCB62B4FAAB34B4D), "item.Labels")            # 49v-jy31n43s2v-wtejc9ypc6-kue
    ChildLink              = TagName((0x1D7FCD10B1143140, 0xB45F595E9B29E11E), "item.child.link.UID")    # 0xg-z6j1d8n650-c8rutcuekm-s8y
    ItemSeries             = TagName((0x647B2CF1DF98191A, 0xFF84E8A015C7C0BB), "item.series")            # 34g-dqg3rws34e-gz178n0bwg-h5v

    SeriesAssetTag         = TagName((0x38365DC6227700FB, 0x39ACAA81B253C797), "item.series.asset.Tag")  # 1s6-tfwd8mr03x-mmc5bh6t57-jwr
    SeriesS2T              = TagName((0x749CA29A38DAA5BF, 0x7139081806CBF2C5), "item.series.S2.UTC64")   # 3nm-kj9nf6unqz-r2f88303dr-wq5

    NodeAttr               = TagName((0x93F76E7915DC92BF, 0x6DD22A7FFF8A1FA8), "node")                # 4my-xr7k5fwkbz-qvnjbgzzsn-7x8

    NodeSealedStatus       = TagName((0x82E0C4CA8CCF5457, 0x64FCB69611D22D16), "node.sealed.Status")  # 42w-32dp36gbjc-q9z5qks8x4-c8q

    ChannelAttr            = TagName((0x3C0BCCB260A85864, 0xC4DF8E1CD985DD60), "channel")                   # 1w1-g6c4s58c1k-d9rwf3mdsc-rc0

    ChannelType            = TagName((0xE16EE14B4532E786, 0x8166AD32465165B0), "channel.type")              # 71e-vhnqj9kwy3-82tpe69352-teh

    ChannelTypeSpreadsheet = TagName((0x1C0062A36805F2FB, 0xC37F9A8B51C0A909), "channel.type.Spreadsheet")  # 0w0-1jb6u05ycx-w6zwuje8w1-b89

    SessionStatusAttr      = TagName((0x7FB381BC8DB19B28, 0xE3EC642BF561552B), "session.Status")  # 3zq-f0vt3ejmdn-f7v345guq2-p9c


class ID:
    SiteDownloads = TagName((0xB30A33823CA36F9E, 0x379DE2617633209C), "http://acme.com/downloads/")  # 5m1-8ts4g53eyg-3g7g2d5v36-84w
    TestNet       = TagName((0x46407EE5F0A5436F, 0xDC383E0601E3386A), "your-scheme://server.com:23382/path")  # 268-1zfcw558er-xsf1y0s0y6-f3b
    BestShow      = TagName((0x9A99BA231EF8C148, 0x63D4A9B0DE7D7F41), "Fraggle.Rock")  # 4um-6x267rss54-67p59q3g7u-zu1


# Bootstrapping node ID
TestingID:      UID = (0x7, 0x8)
# UUID literals — every form accepted by gofrs/uuid.FromString is normalized
# to the same {hi, lo} hex-pair output.  Same UUID, six syntactic spellings:
UUID_Canonical: UID = (0x550E8400E29B41D4, 0xA716446655440000)
UUID_Uppercase: UID = (0x550E8400E29B41D4, 0xA716446655440000)
UUID_Compact:   UID = (0x550E8400E29B41D4, 0xA716446655440000)
UUID_Braced:    UID = (0x550E8400E29B41D4, 0xA716446655440000)
UUID_URN:       UID = (0x550E8400E29B41D4, 0xA716446655440000)
UUID_MixedCase: UID = (0x550E8400E29B41D4, 0xA716446655440000)
# Sentinel UUIDs that downstream callers occasionally need to express.
UUID_Nil:       UID = (0x0000000000000000, 0x0000000000000000)
UUID_Max:       UID = (0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF)
# A distinct UUID, to confirm the parser disambiguates between sources.
HiMom:          UID = (0x6BA7B8109DAD11D1, 0x80B400C04FD430C8)


# Scalar string constants
MaxFraction: int   = 1000000000
HexConst:    int   = 0xFFFFFFFFFFFFFFF0
Pi:          float = 3.14159265358979
SmallPi:     float = 3.14
TwoPi:       float = 3.14159265358979
WholeRate:   float = 1
TinyStep:    float = 1e-09
WholeGain:   float = 2


class SomeFiles:
    WindowsHosts: str = "C:\\Windows\\System32\\drivers\\etc\\hosts"
    UnixHosts:    str = "/etc/hosts"
    MacHosts:     str = "/private/etc/hosts"


class Moar:
    MaxFraction: int   = 1000000000
    TwoPi:       float = 3.14159265358979
    Striiing:    str   = "hello sailor"


class Glyph:
    WebLink:     str = "asset:glyph/web.link"
    DefaultNode: str = "asset:glyph/default.node"


class Herro:
    WebLink:     str = "fooled you"
    DefaultNode: str = "default this"


# ─── Mixed-type group: scalars emit as const, UIDs as var (Go forbids struct ───
# literals in const blocks).  Flat-prefixed by the group name — access is
# `std.SessionContextID` + `std.SessionLaunchPath`.
class Session:
    ContextID:  UID = (0x0, 0x777)
    LaunchPath: str = "/session/start"
