// Code generated by forge const -- DO NOT EDIT.
//
//   source: grammar_test.sdl

export type UID = readonly [bigint, bigint];

export interface TagName {
    readonly id:   UID;
    readonly text: string;
}

export const Name = {
    // ─── This is a big fancy comment, ───────────────────────────────
    AppTag             : { id: [0x9FC2012FD63F847An, 0x51AA55A31D90CD25n], text: "app" },        // 4zs-80kzpjzhjx-53bkpndft1-m95

    AppState           : { id: [0xFAA5BBA978628672n, 0x22BC2C65BFDD460Cn], text: "app.state" },  // 7un-qxuky32htt-25g1ddqzxu-jhd

    // ─── This is a very descriptive comment ─────────────────────────
    // that spans multiple lines to exercise
    // the multi-line doc-comment code path.
    SessionAttr        : { id: [0x5948CA6969CBDF2Fn, 0x01C92A44FA60AB24n], text: "session" },                          // 2t9-356kufcvwr-h3k9b8mx61-bt4

    LoginID            : { id: [0x761CD041F19A871En, 0x588D714F3B7C0369n], text: "session.Login" },                    // 3q3-m843wduhwg-5j3cj9wxrs-0v9
    SessionTag         : { id: [0xCCE00314A1263502n, 0x7A38CD68C10DC759n], text: "session.Tag" },                      // 6dw-01j98966n1-7nf6ee30hv-jut

    LaunchWeb          : { id: [0x7900A4A514A3C61Bn, 0x69753310BD7BA8BBn], text: "session.Tag.www" },                  // 3t0-2kbb553sse-qkx9m22yrr-b5v
    ReallySuperLongName: { id: [0xDB93E07BBD0F0827n, 0xCA42D43B008D32CCn], text: "session.Tag.ReallySuperLongName" },  // 6vk-gh7rg8g10m-wnhqn7d08u-dqd
} satisfies Record<string, TagName>;

export const Attr = {
    ItemAttr              : { id: [0xE8D8BECA5B3BBEB3n, 0x1308458DB27C3504n], text: "item" },                   // 78v-2zdnqtvrut-j6225jqt7s-e84

    ItemLabels            : { id: [0x89DC7C30D083C0B7n, 0xCCB62B4FAAB34B4Dn], text: "item.Labels" },            // 49v-jy31n43s2v-wtejc9ypc6-kue
    ChildLink             : { id: [0x1D7FCD10B1143140n, 0xB45F595E9B29E11En], text: "item.child.link.UID" },    // 0xg-z6j1d8n650-c8rutcuekm-s8y
    ItemSeries            : { id: [0x647B2CF1DF98191An, 0xFF84E8A015C7C0BBn], text: "item.series" },            // 34g-dqg3rws34e-gz178n0bwg-h5v

    SeriesAssetTag        : { id: [0x38365DC6227700FBn, 0x39ACAA81B253C797n], text: "item.series.asset.Tag" },  // 1s6-tfwd8mr03x-mmc5bh6t57-jwr
    SeriesS2T             : { id: [0x749CA29A38DAA5BFn, 0x7139081806CBF2C5n], text: "item.series.S2.UTC64" },   // 3nm-kj9nf6unqz-r2f88303dr-wq5

    ChannelAttr           : { id: [0x3C0BCCB260A85864n, 0xC4DF8E1CD985DD60n], text: "channel" },                   // 1w1-g6c4s58c1k-d9rwf3mdsc-rc0

    ChannelType           : { id: [0xE16EE14B4532E786n, 0x8166AD32465165B0n], text: "channel.type" },              // 71e-vhnqj9kwy3-82tpe69352-teh

    ChannelTypeSpreadsheet: { id: [0x1C0062A36805F2FBn, 0xC37F9A8B51C0A909n], text: "channel.type.Spreadsheet" },  // 0w0-1jb6u05ycx-w6zwuje8w1-b89

    SessionStatusAttr     : { id: [0x7FB381BC8DB19B28n, 0xE3EC642BF561552Bn], text: "session.Status" },  // 3zq-f0vt3ejmdn-f7v345guq2-p9c
} satisfies Record<string, TagName>;

export const ID = {
    SiteDownloads: { id: [0xB30A33823CA36F9En, 0x379DE2617633209Cn], text: "http://acme.com/downloads/" },  // 5m1-8ts4g53eyg-3g7g2d5v36-84w
    TestNet      : { id: [0x46407EE5F0A5436Fn, 0xDC383E0601E3386An], text: "your-scheme://server.com:23382/path" },  // 268-1zfcw558er-xsf1y0s0y6-f3b
    BestShow     : { id: [0x9A99BA231EF8C148n, 0x63D4A9B0DE7D7F41n], text: "Fraggle.Rock" },  // 4um-6x267rss54-67p59q3g7u-zu1
} satisfies Record<string, TagName>;

// Bootstrapping node ID
export const TestingID:      UID = [0x7n, 0x8n];
// UUID literals — every form accepted by gofrs/uuid.FromString is normalized
// to the same {hi, lo} hex-pair output.  Same UUID, six syntactic spellings:
export const UUID_Canonical: UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
export const UUID_Uppercase: UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
export const UUID_Compact:   UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
export const UUID_Braced:    UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
export const UUID_URN:       UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
export const UUID_MixedCase: UID = [0x550E8400E29B41D4n, 0xA716446655440000n];
// Sentinel UUIDs that downstream callers occasionally need to express.
export const UUID_Nil:       UID = [0x0000000000000000n, 0x0000000000000000n];
export const UUID_Max:       UID = [0xFFFFFFFFFFFFFFFFn, 0xFFFFFFFFFFFFFFFFn];
// A distinct UUID, to confirm the parser disambiguates between sources.
export const HiMom:          UID = [0x6BA7B8109DAD11D1n, 0x80B400C04FD430C8n];

// Scalar string constants
export const MaxFraction: bigint = 1000000000n;
export const HexConst:    bigint = 0xFFFFFFFFFFFFFFF0n;
export const Pi:          number = 3.14159265358979;
export const SmallPi:     number = 3.14;
export const TwoPi:       number = 3.14159265358979;
export const WholeRate:   number = 1;
export const TinyStep:    number = 1e-09;
export const WholeGain:   number = 2;

export const SomeFiles = {
    WindowsHosts: "C:\\Windows\\System32\\drivers\\etc\\hosts",
    UnixHosts:    "/etc/hosts",
    MacHosts:     "/private/etc/hosts",
} as const;

export const Moar = {
    MaxFraction: 1000000000n,
    TwoPi:       3.14159265358979,
    Striiing:    "hello sailor",
} as const;

export const Glyph = {
    WebLink:     "asset:glyph/web.link",
    DefaultNode: "asset:glyph/default.node",
} as const;

export const Herro = {
    WebLink:     "fooled you",
    DefaultNode: "default this",
} as const;

// ─── Mixed-type group: scalars emit as const, UIDs as var (Go forbids struct ───
// literals in const blocks).  Flat-prefixed by the group name — access is
// `std.SessionContextID` + `std.SessionLaunchPath`.
export const Session = {
    ContextID:  [0x0n, 0x777n],
    LaunchPath: "/session/start",
} as const;
