// Code generated by forge const -- DO NOT EDIT.
//
//   source: grammar_test.sdl

namespace art.media.platform.std {

    public static partial class Name {

        // ─── This is a big fancy comment, ───────────────────────────────
        public static readonly TagName AppTag   = new(new(0x9FC2012FD63F847A, 0x51AA55A31D90CD25), "app");        // 4ZS80KZPJZHJX53BKPNDFT1M95

        public static readonly TagName AppState = new(new(0xB0E0A1DFE9CF1CE2, 0x6D372EA4CD284F8D), "app.state");  // 5HW2HXZUFG3MJ6UETFNM6KHMWE

        // ─── This is a very descriptive comment ─────────────────────────
        // that spans multiple lines to exercise
        // the multi-line doc-comment code path.
        public static readonly TagName SessionAttr         = new(new(0x5948CA6969CBDF2F, 0x01C92A44FA60AB24), "session");                          // 2T9356KUFCVWRH3K9B8MX61BT4

        public static readonly TagName LoginID             = new(new(0xCC1664C727510447, 0xFBE5F2B6BC492F9D), "session.login");                    // 6D2TKDF9UJ0J3ZRTGKQUY4KCWX
        public static readonly TagName SessionTag          = new(new(0x0F2E0253AA120335, 0x4355B536D92A8B5A), "session.tag");                      // 0G5S157BHK0DUN6PEP6VDKP2UU

        public static readonly TagName LaunchWeb           = new(new(0x972CEB01661BA7F5, 0xC8E19B9BC9291F22), "session.tag.www");                  // 4R5MPH2THVNZUWJSDVMG4KK7T2
        public static readonly TagName ReallySuperLongName = new(new(0xAC9496188C89AB63, 0xF81E6F8687799949), "session.tag.reallysuperlongname");  // 5DKKC1J349PEJZH7MGHU3RM6B9

    }

    public static partial class ID {

        public static readonly TagName HomeWebSite = new(new(0x5BD0C09BE74593E5, 0x0C8059DE0A9D0D50), "https://banana-stand.com");  // 2VU309RTU5KGKHT02TVS59U3BH

        public static readonly TagName WindowsHosts = new(new(0x0C60D6FB30DBF09A, 0x713273FE8FA62A1B), "c:\\Windows\\System32\\drivers\\etc\\hosts");  // 0DD3CGQD6VY2E72DMMZU7UDBHV

        public static readonly TagName KnownHosts = new(new(0xD19FC4D54C2527B0, 0xBF4C697F50B816EC), "file:{$HOME}.ssh/id_rsa");  // 6JMZ2EBM154YSCYM39GX8CH5RD

        public static readonly TagName SiteDownloads = new(new(0x868D828288C7C420, 0x7F486F7861B829C6), "http://acme.enlargements.com/downloads/index.html");  // 46JQ185267SHH7YK3GG1HVHBF6

        public static readonly TagName TestNet = new(new(0x46407EE5F0A5436F, 0xDC383E0601E3386A), "your-scheme://server.com:23382/path");  // 2681ZFCW558ERXSF1Y0S0Y6F3B

        public static readonly TagName BestShow = new(new(0x57B2E51533698C3F, 0x78FFA34D801D6675), "fraggle.rock");  // 2RQCKJBDV9JHZRJZX39Q01UTMP

    }

    public static partial class Moar {
        public static readonly ulong  MaxFraction = 1000000000UL;
        public static readonly double TwoPi       = 3.14159265358979;
        public static readonly string Striiing    = "hello sailor";
    }

    public static partial class Glyph {
        public static readonly string WebLink     = "asset:glyph/web.link";
        public static readonly string DefaultNode = "asset:glyph/default.node";
    }

    public static partial class Herro {
        public static readonly string WebLink     = "fooled you";
        public static readonly string DefaultNode = "default this";
    }

    // ─── Mixed-type group: scalars emit as const, UIDs as var (Go forbids struct ───
    // literals in const blocks).  Flat-prefixed by the group name — access is
    // `std.SessionContextID` + `std.SessionLaunchPath`.
    public static partial class Session {
        public static readonly UID    ContextID  = new(0x0, 0x777);
        public static readonly string LaunchPath = "/session/start";
    }

    public static partial class Const {
        // Scalar string constants
        public static readonly ulong  MaxFraction    = 1000000000UL;
        public static readonly ulong  HexConst       = 0xFFFFFFFFFFFFFFF0UL;
        public static readonly double Pi             = 3.14159265358979;
        public static readonly float  SmallPi        = 3.14f;
        public static readonly double TwoPi          = 3.14159265358979;
        // Bootstrapping node ID
        public static readonly UID    TestingID      = new(0x7, 0x8);
        // UUID literals — every form accepted by gofrs/uuid.FromString is normalized
        // to the same {hi, lo} hex-pair output.  Same UUID, six syntactic spellings:
        public static readonly UID    UUID_Canonical = new(0x550E8400E29B41D4, 0xA716446655440000);
        public static readonly UID    UUID_Uppercase = new(0x550E8400E29B41D4, 0xA716446655440000);
        public static readonly UID    UUID_Compact   = new(0x550E8400E29B41D4, 0xA716446655440000);
        public static readonly UID    UUID_Braced    = new(0x550E8400E29B41D4, 0xA716446655440000);
        public static readonly UID    UUID_URN       = new(0x550E8400E29B41D4, 0xA716446655440000);
        public static readonly UID    UUID_MixedCase = new(0x550E8400E29B41D4, 0xA716446655440000);
        // Sentinel UUIDs that downstream callers occasionally need to express.
        public static readonly UID    UUID_Nil       = new(0x0000000000000000, 0x0000000000000000);
        public static readonly UID    UUID_Max       = new(0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF);
        // A distinct UUID, to confirm the parser disambiguates between sources.
        public static readonly UID    HiMom          = new(0x6BA7B8109DAD11D1, 0x80B400C04FD430C8);
    }

}
