# Code generated by forge const -- DO NOT EDIT.
#
#   source: grammar_test.sdl

from typing import NamedTuple

UID = tuple[int, int]


class TagName(NamedTuple):
    id:      UID
    canonic: str


class Name:
    # ─── This is a big fancy comment, ───────────────────────────────
    AppTag              = TagName((0x9FC2012FD63F847A, 0x51AA55A31D90CD25), "app")        # 4ZS80KZPJZHJX53BKPNDFT1M95

    AppState            = TagName((0xFAA5BBA978628672, 0x22BC2C65BFDD460C), "app.state")  # 7UNQXUKY32HTT25G1DDQZXUJHD

    # ─── This is a very descriptive comment ─────────────────────────
    # that spans multiple lines to exercise
    # the multi-line doc-comment code path.
    SessionAttr         = TagName((0x5948CA6969CBDF2F, 0x01C92A44FA60AB24), "session")                          # 2T9356KUFCVWRH3K9B8MX61BT4

    LoginID             = TagName((0x761CD041F19A871E, 0x588D714F3B7C0369), "session.login")                    # 3Q3M843WDUHWG5J3CJ9WXRS0V9
    SessionTag          = TagName((0xCCE00314A1263502, 0x7A38CD68C10DC759), "session.tag")                      # 6DW01J98966N17NF6EE30HVJUT

    LaunchWeb           = TagName((0x7900A4A514A3C61B, 0x69753310BD7BA8BB), "session.tag.www")                  # 3T02KBB553SSEQKX9M22YRRB5V
    ReallySuperLongName = TagName((0xDB93E07BBD0F0827, 0xCA42D43B008D32CC), "session.tag.reallysuperlongname")  # 6VKGH7RG8G10MWNHQN7D08UDQD


class ID:
    SiteDownloads = TagName((0xB30A33823CA36F9E, 0x379DE2617633209C), "http://acme.com/downloads/")  # 5M18TS4G53EYG3G7G2D5V3684W
    TestNet       = TagName((0x46407EE5F0A5436F, 0xDC383E0601E3386A), "your-scheme://server.com:23382/path")  # 2681ZFCW558ERXSF1Y0S0Y6F3B
    BestShow      = TagName((0x9A99BA231EF8C148, 0x63D4A9B0DE7D7F41), "fraggle.rock")  # 4UM6X267RSS5467P59Q3G7UZU1


# Bootstrapping node ID
TestingID:      UID = (0x7, 0x8)
# UUID literals — every form accepted by gofrs/uuid.FromString is normalized
# to the same {hi, lo} hex-pair output.  Same UUID, six syntactic spellings:
UUID_Canonical: UID = (0x550E8400E29B41D4, 0xA716446655440000)
UUID_Uppercase: UID = (0x550E8400E29B41D4, 0xA716446655440000)
UUID_Compact:   UID = (0x550E8400E29B41D4, 0xA716446655440000)
UUID_Braced:    UID = (0x550E8400E29B41D4, 0xA716446655440000)
UUID_URN:       UID = (0x550E8400E29B41D4, 0xA716446655440000)
UUID_MixedCase: UID = (0x550E8400E29B41D4, 0xA716446655440000)
# Sentinel UUIDs that downstream callers occasionally need to express.
UUID_Nil:       UID = (0x0000000000000000, 0x0000000000000000)
UUID_Max:       UID = (0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF)
# A distinct UUID, to confirm the parser disambiguates between sources.
HiMom:          UID = (0x6BA7B8109DAD11D1, 0x80B400C04FD430C8)


# Scalar string constants
MaxFraction: int   = 1000000000
HexConst:    int   = 0xFFFFFFFFFFFFFFF0
Pi:          float = 3.14159265358979
SmallPi:     float = 3.14
TwoPi:       float = 3.14159265358979


class SomeFiles:
    WindowsHosts: str = "C:\\Windows\\System32\\drivers\\etc\\hosts"
    UnixHosts:    str = "/etc/hosts"
    MacHosts:     str = "/private/etc/hosts"


class Moar:
    MaxFraction: int   = 1000000000
    TwoPi:       float = 3.14159265358979
    Striiing:    str   = "hello sailor"


class Glyph:
    WebLink:     str = "asset:glyph/web.link"
    DefaultNode: str = "asset:glyph/default.node"


class Herro:
    WebLink:     str = "fooled you"
    DefaultNode: str = "default this"


# ─── Mixed-type group: scalars emit as const, UIDs as var (Go forbids struct ───
# literals in const blocks).  Flat-prefixed by the group name — access is
# `std.SessionContextID` + `std.SessionLaunchPath`.
class Session:
    ContextID:  UID = (0x0, 0x777)
    LaunchPath: str = "/session/start"
