// Code generated by forge const -- DO NOT EDIT.
//
//   source: grammar_test.sdl

#pragma once

#include <stdint.h>

#ifndef FORGE_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define FORGE_UNUSED __attribute__((unused))
#else
#define FORGE_UNUSED
#endif
#endif

#ifndef FORGE_CONSTS_TYPES
#define FORGE_CONSTS_TYPES

typedef struct {
    uint64_t hi;
    uint64_t lo;
} TagUID;

typedef struct {
    TagUID      id;
    const char *canonic;
} TagName;

#endif // FORGE_CONSTS_TYPES

static const struct {
    TagName AppTag;
    TagName AppState;
    TagName SessionAttr;
    TagName LoginID;
    TagName SessionTag;
    TagName LaunchWeb;
    TagName ReallySuperLongName;
} Name FORGE_UNUSED = {
    // ─── This is a big fancy comment, ───────────────────────────────
    .AppTag              = { { 0x9FC2012FD63F847A, 0x51AA55A31D90CD25 }, "app" },        // 4ZS80KZPJZHJX53BKPNDFT1M95

    .AppState            = { { 0xB0E0A1DFE9CF1CE2, 0x6D372EA4CD284F8D }, "app.state" },  // 5HW2HXZUFG3MJ6UETFNM6KHMWE

    // ─── This is a very descriptive comment ─────────────────────────
    // that spans multiple lines to exercise
    // the multi-line doc-comment code path.
    .SessionAttr         = { { 0x5948CA6969CBDF2F, 0x01C92A44FA60AB24 }, "session" },                          // 2T9356KUFCVWRH3K9B8MX61BT4

    .LoginID             = { { 0xCC1664C727510447, 0xFBE5F2B6BC492F9D }, "session.login" },                    // 6D2TKDF9UJ0J3ZRTGKQUY4KCWX
    .SessionTag          = { { 0x0F2E0253AA120335, 0x4355B536D92A8B5A }, "session.tag" },                      // 0G5S157BHK0DUN6PEP6VDKP2UU

    .LaunchWeb           = { { 0x972CEB01661BA7F5, 0xC8E19B9BC9291F22 }, "session.tag.www" },                  // 4R5MPH2THVNZUWJSDVMG4KK7T2
    .ReallySuperLongName = { { 0xAC9496188C89AB63, 0xF81E6F8687799949 }, "session.tag.reallysuperlongname" },  // 5DKKC1J349PEJZH7MGHU3RM6B9
};

static const struct {
    TagName SiteDownloads;
    TagName TestNet;
    TagName BestShow;
} ID FORGE_UNUSED = {
    .SiteDownloads = { { 0xB30A33823CA36F9E, 0x379DE2617633209C }, "http://acme.com/downloads/" },  // 5M18TS4G53EYG3G7G2D5V3684W
    .TestNet       = { { 0x46407EE5F0A5436F, 0xDC383E0601E3386A }, "your-scheme://server.com:23382/path" },  // 2681ZFCW558ERXSF1Y0S0Y6F3B
    .BestShow      = { { 0x57B2E51533698C3F, 0x78FFA34D801D6675 }, "fraggle.rock" },  // 2RQCKJBDV9JHZRJZX39Q01UTMP
};

static const struct {
    const char *WindowsHosts;
    const char *UnixHosts;
    const char *MacHosts;
} SomeFiles FORGE_UNUSED = {
    .WindowsHosts = "C:\\Windows\\System32\\drivers\\etc\\hosts",
    .UnixHosts    = "/etc/hosts",
    .MacHosts     = "/private/etc/hosts",
};

static const struct {
    uint64_t    MaxFraction;
    double      TwoPi;
    const char *Striiing;
} Moar FORGE_UNUSED = {
    .MaxFraction = 1000000000ULL,
    .TwoPi       = 3.14159265358979,
    .Striiing    = "hello sailor",
};

static const struct {
    const char *WebLink;
    const char *DefaultNode;
} Glyph FORGE_UNUSED = {
    .WebLink     = "asset:glyph/web.link",
    .DefaultNode = "asset:glyph/default.node",
};

static const struct {
    const char *WebLink;
    const char *DefaultNode;
} Herro FORGE_UNUSED = {
    .WebLink     = "fooled you",
    .DefaultNode = "default this",
};

// ─── Mixed-type group: scalars emit as const, UIDs as var (Go forbids struct ───
// literals in const blocks).  Flat-prefixed by the group name — access is
// `std.SessionContextID` + `std.SessionLaunchPath`.
static const struct {
    TagUID      ContextID;
    const char *LaunchPath;
} Session FORGE_UNUSED = {
    .ContextID  = { 0x0, 0x777 },
    .LaunchPath = "/session/start",
};

static const struct {
    uint64_t MaxFraction;
    uint64_t HexConst;
    double   Pi;
    float    SmallPi;
    double   TwoPi;
    TagUID   TestingID;
    TagUID   UUID_Canonical;
    TagUID   UUID_Uppercase;
    TagUID   UUID_Compact;
    TagUID   UUID_Braced;
    TagUID   UUID_URN;
    TagUID   UUID_MixedCase;
    TagUID   UUID_Nil;
    TagUID   UUID_Max;
    TagUID   HiMom;
} Const FORGE_UNUSED = {
    // Scalar string constants
    .MaxFraction    = 1000000000ULL,
    .HexConst       = 0xFFFFFFFFFFFFFFF0ULL,
    .Pi             = 3.14159265358979,
    .SmallPi        = 3.14f,
    .TwoPi          = 3.14159265358979,
    // Bootstrapping node ID
    .TestingID      = { 0x7, 0x8 },
    // UUID literals — every form accepted by gofrs/uuid.FromString is normalized
    // to the same {hi, lo} hex-pair output.  Same UUID, six syntactic spellings:
    .UUID_Canonical = { 0x550E8400E29B41D4, 0xA716446655440000 },
    .UUID_Uppercase = { 0x550E8400E29B41D4, 0xA716446655440000 },
    .UUID_Compact   = { 0x550E8400E29B41D4, 0xA716446655440000 },
    .UUID_Braced    = { 0x550E8400E29B41D4, 0xA716446655440000 },
    .UUID_URN       = { 0x550E8400E29B41D4, 0xA716446655440000 },
    .UUID_MixedCase = { 0x550E8400E29B41D4, 0xA716446655440000 },
    // Sentinel UUIDs that downstream callers occasionally need to express.
    .UUID_Nil       = { 0x0000000000000000, 0x0000000000000000 },
    .UUID_Max       = { 0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF },
    // A distinct UUID, to confirm the parser disambiguates between sources.
    .HiMom          = { 0x6BA7B8109DAD11D1, 0x80B400C04FD430C8 },
};
