// Code generated by forge const -- DO NOT EDIT.
//
//   source: grammar_test.sdl

#pragma once

#include <stdint.h>

#ifndef FORGE_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define FORGE_UNUSED __attribute__((unused))
#else
#define FORGE_UNUSED
#endif
#endif

#ifndef FORGE_CONSTS_TYPES
#define FORGE_CONSTS_TYPES

typedef struct {
    uint64_t hi;
    uint64_t lo;
} TagUID;

typedef struct {
    TagUID      id;
    const char *canonic;
} TagName;

#endif // FORGE_CONSTS_TYPES

static const struct {
    TagName AppTag;
    TagName AppState;
    TagName SessionAttr;
    TagName LoginID;
    TagName SessionTag;
    TagName LaunchWeb;
    TagName ReallySuperLongName;
} Name FORGE_UNUSED = {
    // ─── This is a big fancy comment, ───────────────────────────────
    .AppTag              = { { 0x9FC2012FD63F847A, 0x51AA55A31D90CD25 }, "app" },        // 4ZS80KZPJZHJX53BKPNDFT1M95

    .AppState            = { { 0xFAA5BBA978628672, 0x22BC2C65BFDD460C }, "app.state" },  // 7UNQXUKY32HTT25G1DDQZXUJHD

    // ─── This is a very descriptive comment ─────────────────────────
    // that spans multiple lines to exercise
    // the multi-line doc-comment code path.
    .SessionAttr         = { { 0x5948CA6969CBDF2F, 0x01C92A44FA60AB24 }, "session" },                          // 2T9356KUFCVWRH3K9B8MX61BT4

    .LoginID             = { { 0x761CD041F19A871E, 0x588D714F3B7C0369 }, "session.login" },                    // 3Q3M843WDUHWG5J3CJ9WXRS0V9
    .SessionTag          = { { 0xCCE00314A1263502, 0x7A38CD68C10DC759 }, "session.tag" },                      // 6DW01J98966N17NF6EE30HVJUT

    .LaunchWeb           = { { 0x7900A4A514A3C61B, 0x69753310BD7BA8BB }, "session.tag.www" },                  // 3T02KBB553SSEQKX9M22YRRB5V
    .ReallySuperLongName = { { 0xDB93E07BBD0F0827, 0xCA42D43B008D32CC }, "session.tag.reallysuperlongname" },  // 6VKGH7RG8G10MWNHQN7D08UDQD
};

static const struct {
    TagName SiteDownloads;
    TagName TestNet;
    TagName BestShow;
} ID FORGE_UNUSED = {
    .SiteDownloads = { { 0xB30A33823CA36F9E, 0x379DE2617633209C }, "http://acme.com/downloads/" },  // 5M18TS4G53EYG3G7G2D5V3684W
    .TestNet       = { { 0x46407EE5F0A5436F, 0xDC383E0601E3386A }, "your-scheme://server.com:23382/path" },  // 2681ZFCW558ERXSF1Y0S0Y6F3B
    .BestShow      = { { 0x9A99BA231EF8C148, 0x63D4A9B0DE7D7F41 }, "fraggle.rock" },  // 4UM6X267RSS5467P59Q3G7UZU1
};

static const struct {
    const char *WindowsHosts;
    const char *UnixHosts;
    const char *MacHosts;
} SomeFiles FORGE_UNUSED = {
    .WindowsHosts = "C:\\Windows\\System32\\drivers\\etc\\hosts",
    .UnixHosts    = "/etc/hosts",
    .MacHosts     = "/private/etc/hosts",
};

static const struct {
    uint64_t    MaxFraction;
    double      TwoPi;
    const char *Striiing;
} Moar FORGE_UNUSED = {
    .MaxFraction = 1000000000ULL,
    .TwoPi       = 3.14159265358979,
    .Striiing    = "hello sailor",
};

static const struct {
    const char *WebLink;
    const char *DefaultNode;
} Glyph FORGE_UNUSED = {
    .WebLink     = "asset:glyph/web.link",
    .DefaultNode = "asset:glyph/default.node",
};

static const struct {
    const char *WebLink;
    const char *DefaultNode;
} Herro FORGE_UNUSED = {
    .WebLink     = "fooled you",
    .DefaultNode = "default this",
};

// ─── Mixed-type group: scalars emit as const, UIDs as var (Go forbids struct ───
// literals in const blocks).  Flat-prefixed by the group name — access is
// `std.SessionContextID` + `std.SessionLaunchPath`.
static const struct {
    TagUID      ContextID;
    const char *LaunchPath;
} Session FORGE_UNUSED = {
    .ContextID  = { 0x0, 0x777 },
    .LaunchPath = "/session/start",
};

static const struct {
    uint64_t MaxFraction;
    uint64_t HexConst;
    double   Pi;
    float    SmallPi;
    double   TwoPi;
    TagUID   TestingID;
    TagUID   UUID_Canonical;
    TagUID   UUID_Uppercase;
    TagUID   UUID_Compact;
    TagUID   UUID_Braced;
    TagUID   UUID_URN;
    TagUID   UUID_MixedCase;
    TagUID   UUID_Nil;
    TagUID   UUID_Max;
    TagUID   HiMom;
} Const FORGE_UNUSED = {
    // Scalar string constants
    .MaxFraction    = 1000000000ULL,
    .HexConst       = 0xFFFFFFFFFFFFFFF0ULL,
    .Pi             = 3.14159265358979,
    .SmallPi        = 3.14f,
    .TwoPi          = 3.14159265358979,
    // Bootstrapping node ID
    .TestingID      = { 0x7, 0x8 },
    // UUID literals — every form accepted by gofrs/uuid.FromString is normalized
    // to the same {hi, lo} hex-pair output.  Same UUID, six syntactic spellings:
    .UUID_Canonical = { 0x550E8400E29B41D4, 0xA716446655440000 },
    .UUID_Uppercase = { 0x550E8400E29B41D4, 0xA716446655440000 },
    .UUID_Compact   = { 0x550E8400E29B41D4, 0xA716446655440000 },
    .UUID_Braced    = { 0x550E8400E29B41D4, 0xA716446655440000 },
    .UUID_URN       = { 0x550E8400E29B41D4, 0xA716446655440000 },
    .UUID_MixedCase = { 0x550E8400E29B41D4, 0xA716446655440000 },
    // Sentinel UUIDs that downstream callers occasionally need to express.
    .UUID_Nil       = { 0x0000000000000000, 0x0000000000000000 },
    .UUID_Max       = { 0xFFFFFFFFFFFFFFFF, 0xFFFFFFFFFFFFFFFF },
    // A distinct UUID, to confirm the parser disambiguates between sources.
    .HiMom          = { 0x6BA7B8109DAD11D1, 0x80B400C04FD430C8 },
};
