package consts

import (
	"fmt"
	"strings"
)

// CSharpEmitter renders the C# target.
type CSharpEmitter struct{}

func (CSharpEmitter) Generate(src *ConstFile, opts *GenOpts) ([]byte, error) {
	return GenerateCSharp(src, opts)
}
func (CSharpEmitter) Info() EmitterInfo {
	return EmitterInfo{
		Language:  "C#",
		Extension: ".cs",
		Flag:      "csharp_out",
	}
}

// GenerateCSharp emits C# source code from a parsed .consts.sdl file.
func GenerateCSharp(src *ConstFile, opts *GenOpts) ([]byte, error) {
	if opts == nil {
		opts = &GenOpts{}
	}

	ns := src.GetOption("csharp_namespace")
	if ns == "" {
		return nil, fmt.Errorf("missing option csharp_namespace")
	}

	// Namespace body is built separately, then indented one level inside the
	// block-scoped namespace braces.
	var body strings.Builder

	decls := categorize(src)

	// Attr registration rides the same file (ZO §4.8 compiled): a generated
	// attrID → parser table the display layer reads through.
	attrRegs, err := classifyAttrs(src)
	if err != nil {
		return nil, err
	}

	// Emit tags blocks — do NOT fold in top-level UIDs.  Each tags block is a
	// pure tag.Name namespace; UIDs get their own home in the Const class or
	// in whatever ConstGroup they were declared in.
	for _, tb := range decls.Tags {
		emitCSharpTagsBlock(&body, tb)
	}

	// Emit grouped constants (scalars + UIDs coexist as public members).
	for _, grp := range decls.Groups {
		emitCSharpConstClass(&body, grp.Name, grp.Members, grp.LeadComment)
	}

	// Merge top-level scalars and top-level UIDs into a single "Const" class.
	// No section-header hoist from the first member's comment — per-member
	// doc comments stay inline alongside each field.
	topMembers := append([]*ConstDecl{}, decls.Scalars...)
	topMembers = append(topMembers, decls.UIDs...)
	if len(topMembers) > 0 {
		emitCSharpConstClass(&body, "Const", topMembers, "")
	}

	if len(attrRegs) > 0 {
		if err := emitCSharpAttrRegistry(&body, attrRegs); err != nil {
			return nil, err
		}
	}

	var buf strings.Builder

	// Header
	buf.WriteString("// Code generated by forge const -- DO NOT EDIT.\n")
	if opts.SourceName != "" {
		buf.WriteString("//\n")
		buf.WriteString("//   source: " + opts.SourceName + "\n")
	}
	if len(attrRegs) > 0 {
		buf.WriteString("\nusing Google.Protobuf;\n")
	}

	// Block-scoped namespace (C# 9 compatible): class bodies are indented one
	// level inside the braces.
	buf.WriteString("\nnamespace " + ns + " {\n")
	buf.WriteString(indentBlock(strings.TrimPrefix(body.String(), "\n"), "    "))
	buf.WriteString("}\n")

	return []byte(buf.String()), nil
}

// indentBlock prefixes every non-empty line of text with indent.  Blank lines
// are left untouched so no trailing whitespace is introduced.
func indentBlock(text, indent string) string {
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		if line != "" {
			lines[i] = indent + line
		}
	}
	return strings.Join(lines, "\n")
}

// emitCSharpTagsBlock emits the partial class wrapping all tag entries.
// UIDs declared at file scope do NOT fold in here; they belong in their own
// namespace (Const class or their ConstGroup's class).
func emitCSharpTagsBlock(buf *strings.Builder, tb *TagsBlock) {
	buf.WriteString("\npublic static partial class " + tb.Name + " {\n")

	sections := buildTagSections(tb.Entries)

	// Measure max var name width across all entries for shared column alignment
	maxVar := 0
	for _, sec := range sections {
		for _, entry := range sec.entries {
			if n := len(entry.varName); n > maxVar {
				maxVar = n
			}
		}
	}

	for i := range sections {
		if blankBetweenSections(sections, i) {
			buf.WriteString("\n")
		}
		emitCSharpTagSection(buf, &sections[i], maxVar)
	}

	buf.WriteString("}\n")
}

// emitCSharpTagSection writes one alignment group of C# tag entries.
// maxVar is the block-global var name width so flat sections align together.
func emitCSharpTagSection(buf *strings.Builder, sec *tagSection, maxVar int) {
	if len(sec.entries) == 0 {
		return
	}

	const indent = "    "

	// Section divider
	if sec.comment != "" {
		emitSectionHeader(buf, sec.comment, indent+"// ")
	}

	// Tag entries are always `static readonly Name` (a struct ctor is not a
	// compile-time constant, so they can't be `const`).
	expr := func(entry *resolvedEntry) string {
		return "public static readonly Name " + padRight(entry.varName, maxVar) + " = " + csTagExpr(entry) + ";"
	}

	// First pass: measure code column width for trailing-comment alignment
	maxCode := 0
	for i := range sec.entries {
		if n := len(expr(&sec.entries[i])); n > maxCode {
			maxCode = n
		}
	}

	// Second pass: emit aligned entries (text is in the literal; the trailing
	// comment is just Base32)
	for i := range sec.entries {
		entry := &sec.entries[i]

		if entry.leadComment != "" && entry.leadComment != sec.comment {
			for _, line := range strings.Split(entry.leadComment, "\n") {
				buf.WriteString(indent + "// " + line + "\n")
			}
		}

		buf.WriteString(indent + padRight(expr(entry), maxCode) + "  // " + entry.base32 + "\n")

		if entry.isParent {
			buf.WriteString("\n")
		}
	}
}

// csTagExpr builds the C# Name expression for a tag entry.
func csTagExpr(entry *resolvedEntry) string {
	return fmt.Sprintf("new(new(0x%016X, 0x%016X), %s)", entry.uidHi, entry.uidLo, csharpQuote(entry.text))
}

// emitCSharpAttrRegistry writes the generated attrID → parser table — every
// declared attr paired with its message parser and edit flow (ZO §4.8), so
// the Inspector's decode layer needs no hand list; curated display metadata
// stays a hand overlay (AttrSpecs).
func emitCSharpAttrRegistry(buf *strings.Builder, regs []attrReg) error {
	const indent = "    "

	for _, reg := range regs {
		if reg.msg.csNamespace == "" {
			return fmt.Errorf("attr %q (%s): message %s has no csharp_namespace in its .proto",
				reg.varName, reg.text, reg.msg.name)
		}
	}

	buf.WriteString("\n// Every attr above whose trailing name word is a message type appears\n")
	buf.WriteString("// here (ZO §4.8); a `: tape` flag in the SDL declares EditFlow.Tape,\n")
	buf.WriteString("// unmarked attrs fold.\n")
	buf.WriteString("public static partial class AttrRegistry {\n\n")
	buf.WriteString(indent + "public struct Entry {\n")
	buf.WriteString(indent + indent + "public Name          Attr;\n")
	buf.WriteString(indent + indent + "public MessageParser Parser;\n")
	buf.WriteString(indent + indent + "public EditFlow      Flow;\n")
	buf.WriteString(indent + "}\n\n")
	buf.WriteString(indent + "public static readonly Entry[] Attrs = {\n")

	// Measure the attr-ref column for alignment.
	maxAttr := 0
	for _, reg := range regs {
		if n := len(reg.varName); n > maxAttr {
			maxAttr = n
		}
	}
	for _, reg := range regs {
		flow := "Fold"
		if reg.isTape {
			flow = "Tape"
		}
		parserRef := "global::" + reg.msg.csNamespace + "." + reg.msg.name + ".Parser"
		buf.WriteString(indent + indent + "new() { Attr = Attr." +
			padRight(reg.varName+",", maxAttr+1) +
			" Parser = " + parserRef + ", Flow = EditFlow." + flow + " },\n")
	}
	buf.WriteString(indent + "};\n")
	buf.WriteString("}\n")

	emitCSharpBindAccessors(buf, regs)
	return nil
}

// emitCSharpBindAccessors writes the flag-typed accessor per registered
// attr: a fold attr yields only the FoldBinding shape, a tape attr only the
// TapeBinding family — consuming a tape through a FoldBinding is
// uncompilable.  Accessor + type only, no behavior.
func emitCSharpBindAccessors(buf *strings.Builder, regs []attrReg) {
	const indent = "    "

	type accessor struct {
		method  string
		binding string
		attrRef string
	}
	var accessors []accessor
	for _, reg := range regs {
		valueRef := "global::" + reg.msg.csNamespace + "." + reg.msg.name
		attrRef := "Attr." + reg.varName
		if reg.isTape {
			accessors = append(accessors,
				accessor{reg.varName + "Window", "TapeBinding<" + valueRef + ">", attrRef},
				accessor{reg.varName + "Tail", "TapeTailBinding<" + valueRef + ">", attrRef})
		} else {
			accessors = append(accessors,
				accessor{reg.varName, "FoldBinding<" + valueRef + ">", attrRef})
		}
	}

	maxMethod, maxBinding := 0, 0
	for _, acc := range accessors {
		maxMethod = max(maxMethod, len(acc.method))
		maxBinding = max(maxBinding, len(acc.binding))
	}

	buf.WriteString("\n// Flag-typed accessors: the declared storage style picks the binding\n")
	buf.WriteString("// shape at compile time.\n")
	buf.WriteString("public static partial class Bind {\n")
	for _, acc := range accessors {
		buf.WriteString(indent + "public static " + padRight(acc.binding, maxBinding) +
			" " + padRight(acc.method+"()", maxMethod+2) + " => new(" + acc.attrRef + ");\n")
	}
	buf.WriteString("}\n")
}

// emitCSharpConstClass writes a partial class of scalar / UID constants.
// Compile-time scalars emit as `public const`; UIDs (a struct ctor, not a
// constant expression) emit as `public static readonly`.  When both kinds
// appear in one class the modifier forms a column of its own so the type and
// name columns still line up.
func emitCSharpConstClass(buf *strings.Builder, className string, decls []*ConstDecl, sectionComment string) {
	if len(decls) == 0 {
		return
	}

	const inner = "    "

	buf.WriteString("\n")
	if sectionComment != "" {
		emitSectionHeader(buf, sectionComment, "// ")
	}
	buf.WriteString("public static partial class " + className + " {\n")

	// Measure modifier, type, and var-name widths for alignment.
	maxMod, maxType, maxVar := 0, 0, 0
	for _, member := range decls {
		maxMod = max(maxMod, len(csharpModifier(member.Type)))
		maxType = max(maxType, len(csharpType(member.Type)))
		maxVar = max(maxVar, len(member.VarName))
	}

	code := func(member *ConstDecl) string {
		return "public " + padRight(csharpModifier(member.Type), maxMod) +
			" " + padRight(csharpType(member.Type), maxType) +
			" " + padRight(member.VarName, maxVar) +
			" = " + csharpConstValue(member.Type, member.Value) + ";"
	}

	// Measure full code width for trailing-comment alignment.
	maxCode := 0
	for i := range decls {
		if n := len(code(decls[i])); n > maxCode {
			maxCode = n
		}
	}

	for _, member := range decls {
		// Per-entry doc comment
		if member.LeadComment != "" && member.LeadComment != sectionComment {
			for _, ln := range strings.Split(member.LeadComment, "\n") {
				buf.WriteString(inner + "// " + ln + "\n")
			}
		}

		line := inner + code(member)
		if member.TrailComment != "" {
			line = inner + padRight(code(member), maxCode) + "  // " + member.TrailComment
		}
		buf.WriteString(line + "\n")
	}

	buf.WriteString("}\n")
}

// csharpModifier picks the field modifier for a member type: compile-time
// scalars are `const`; UIDs are a struct ctor and must be `static readonly`.
func csharpModifier(typeName string) string {
	if typeName == "uid" {
		return "static readonly"
	}
	return "const"
}

func csharpType(typeName string) string {
	switch typeName {
	case "string":
		return "string"
	case "int32":
		return "int"
	case "int64":
		return "long"
	case "uint32":
		return "uint"
	case "uint64", "fixed64":
		return "ulong"
	case "float32", "float":
		return "float"
	case "float64", "double":
		return "double"
	case "uid":
		return "UID"
	default:
		return typeName
	}
}

func csharpConstValue(typeName string, val *Value) string {
	if val.UIDPair != nil {
		return fmt.Sprintf("new(%s, %s)", val.UIDPair.Hi, val.UIDPair.Lo)
	}
	if val.String != nil {
		return csharpQuote(*val.String)
	}
	if val.Float != nil {
		switch typeName {
		case "float32", "float":
			return fmt.Sprintf("%gf", *val.Float)
		default:
			return floatLiteral(*val.Float)
		}
	}
	if val.Hex != nil {
		hex := *val.Hex
		switch typeName {
		case "uint64", "fixed64":
			return hex + "UL"
		case "uint32":
			return hex + "U"
		case "int64":
			return hex + "L"
		case "float32", "float":
			return hex + "f"
		default:
			return hex
		}
	}
	if val.Int != nil {
		switch typeName {
		case "uint64", "fixed64":
			return fmt.Sprintf("%dUL", *val.Int)
		case "uint32":
			return fmt.Sprintf("%dU", *val.Int)
		case "int64":
			return fmt.Sprintf("%dL", *val.Int)
		case "float32", "float":
			return fmt.Sprintf("%df", *val.Int)
		default:
			return fmt.Sprintf("%d", *val.Int)
		}
	}
	return "null"
}
