package consts

import (
	"fmt"
	"strings"
)

// GenerateTypeScript emits TypeScript source code from a parsed .consts.sdl file.
func GenerateTypeScript(cf *ConstFile, opts *GenOpts) ([]byte, error) {
	if opts == nil {
		opts = &GenOpts{}
	}

	var buf strings.Builder

	// Header
	buf.WriteString("// Code generated by forge const -- DO NOT EDIT.\n")
	if opts.SourceName != "" {
		buf.WriteString("//\n")
		buf.WriteString("//   source: " + opts.SourceName + "\n")
	}

	ds := categorize(cf)

	// Self-contained type declarations — TypeScript has no amp tag runtime, so
	// the UID tuple and TagName shape are emitted inline.  TagName references
	// UID; uid consts need UID alone.
	if ds.needsUID() {
		buf.WriteString("\nexport type UID = readonly [bigint, bigint];\n")
	}
	if ds.needsTagName() {
		buf.WriteString("\nexport interface TagName {\n")
		buf.WriteString("    readonly id:      UID;\n")
		buf.WriteString("    readonly canonic: string;\n")
		buf.WriteString("}\n")
	}

	for _, tb := range ds.Tags {
		emitTSTagsBlock(&buf, tb)
	}

	// Top-level UID consts, then scalar consts — each an aligned run of
	// `export const` declarations.
	if len(ds.UIDs) > 0 {
		emitTSExports(&buf, ds.UIDs)
	}
	if len(ds.Scalars) > 0 {
		emitTSExports(&buf, ds.Scalars)
	}

	// Grouped constants emit as `as const` object literals; access is Group.Member.
	for _, grp := range ds.Groups {
		emitTSGroup(&buf, grp)
	}

	return []byte(buf.String()), nil
}

// emitTSTagsBlock writes a tags block as an `export const` object literal whose
// values are pre-computed TagName records — zero runtime hash cost.
func emitTSTagsBlock(buf *strings.Builder, tb *TagsBlock) {
	sections := buildTagSections(tb.Entries)

	// Measure max var name width across all entries for shared column alignment
	maxVar := 0
	for _, sec := range sections {
		for _, entry := range sec.entries {
			if n := len(entry.varName); n > maxVar {
				maxVar = n
			}
		}
	}

	buf.WriteString("\nexport const " + tb.Name + " = {\n")
	for i := range sections {
		if blankBetweenSections(sections, i) {
			buf.WriteString("\n")
		}
		emitTSTagSection(buf, &sections[i], maxVar)
	}
	buf.WriteString("} satisfies Record<string, TagName>;\n")
}

// emitTSTagSection writes one alignment group inside the object literal.
func emitTSTagSection(buf *strings.Builder, sec *tagSection, maxVar int) {
	if len(sec.entries) == 0 {
		return
	}

	// Section divider from source comment
	if sec.comment != "" {
		emitSectionHeader(buf, sec.comment, "    // ")
	}

	// First pass: build formatted lines and measure code column width
	maxCode := 0

	type tsLine struct {
		code   string
		base32 string
	}
	lines := make([]tsLine, len(sec.entries))
	for i, entry := range sec.entries {
		varPad := strings.Repeat(" ", maxVar-len(entry.varName))
		lines[i] = tsLine{
			code:   entry.varName + varPad + ": " + tsTagExpr(&entry) + ",",
			base32: entry.base32,
		}
		if n := len(lines[i].code); n > maxCode {
			maxCode = n
		}
	}

	// Second pass: emit aligned entries (canonic is visible in the literal, comment is just Base32)
	for i, entry := range sec.entries {
		line := lines[i]

		// Per-entry doc comment (skip if same text as section header)
		if entry.leadComment != "" && entry.leadComment != sec.comment {
			for _, cl := range strings.Split(entry.leadComment, "\n") {
				buf.WriteString("    // " + cl + "\n")
			}
		}

		codePad := strings.Repeat(" ", maxCode-len(line.code))

		buf.WriteString("    " + line.code + codePad + "  // " + line.base32 + "\n")

		// Visual break after parent entries (children follow)
		if entry.isParent {
			buf.WriteString("\n")
		}
	}
}

// tsTagExpr builds the TypeScript TagName record for a tag entry.
// All entries emit as pre-computed literals.
func tsTagExpr(entry *resolvedEntry) string {
	return fmt.Sprintf("{ id: [0x%016Xn, 0x%016Xn], canonic: %q }", entry.uidHi, entry.uidLo, entry.canonic)
}

// emitTSExports writes a run of top-level `export const` declarations with an
// aligned name and type column.  Per-decl doc comments stay inline.
func emitTSExports(buf *strings.Builder, decls []*ConstDecl) {
	if len(decls) == 0 {
		return
	}

	buf.WriteString("\n")

	// Measure name and type widths for alignment
	maxName := 0
	maxType := 0
	for _, decl := range decls {
		if n := len(decl.VarName); n > maxName {
			maxName = n
		}
		if n := len(tsScalarType(decl.Type)); n > maxType {
			maxType = n
		}
	}

	for _, decl := range decls {
		// Individual doc comment
		if decl.LeadComment != "" {
			for _, cl := range strings.Split(decl.LeadComment, "\n") {
				buf.WriteString("// " + cl + "\n")
			}
		}

		tsType := tsScalarType(decl.Type)
		namePad := strings.Repeat(" ", maxName-len(decl.VarName))
		typePad := strings.Repeat(" ", maxType-len(tsType))

		line := "export const " + decl.VarName + ":" + namePad + " " + tsType + typePad + " = " + tsConstValue(decl.Type, decl.Value) + ";"
		if decl.TrailComment != "" {
			line += "  // " + decl.TrailComment
		}
		buf.WriteString(line + "\n")
	}
}

// emitTSGroup writes a const group as a single `as const` object literal.
func emitTSGroup(buf *strings.Builder, grp *ConstGroup) {
	if len(grp.Members) == 0 {
		return
	}

	buf.WriteString("\n")
	if grp.LeadComment != "" {
		emitSectionHeader(buf, grp.LeadComment, "// ")
	}

	// Measure member name width for alignment
	maxName := 0
	for _, member := range grp.Members {
		if n := len(member.VarName); n > maxName {
			maxName = n
		}
	}

	buf.WriteString("export const " + grp.Name + " = {\n")
	for _, member := range grp.Members {
		// Per-member doc comment (skip if already used as section header)
		if member.LeadComment != "" && member.LeadComment != grp.LeadComment {
			for _, cl := range strings.Split(member.LeadComment, "\n") {
				buf.WriteString("    // " + cl + "\n")
			}
		}

		namePad := strings.Repeat(" ", maxName-len(member.VarName))
		line := "    " + member.VarName + ":" + namePad + " " + tsConstValue(member.Type, member.Value) + ","
		if member.TrailComment != "" {
			line += "  // " + member.TrailComment
		}
		buf.WriteString(line + "\n")
	}
	buf.WriteString("} as const;\n")
}

// tsScalarType maps a .consts.sdl scalar type to its idiomatic TypeScript type.
// 64-bit integers map to bigint to preserve values beyond 2^53.
func tsScalarType(typeName string) string {
	switch typeName {
	case "string":
		return "string"
	case "int32", "uint32":
		return "number"
	case "int64", "uint64", "fixed64":
		return "bigint"
	case "float32", "float", "float64", "double":
		return "number"
	case "uid":
		return "UID"
	default:
		return typeName
	}
}

// tsConstValue formats a Value for TypeScript output.
func tsConstValue(typeName string, val *Value) string {
	if val.UIDPair != nil {
		return fmt.Sprintf("[%sn, %sn]", val.UIDPair.Hi, val.UIDPair.Lo)
	}
	if val.String != nil {
		return tsQuote(*val.String)
	}
	if val.Float != nil {
		return fmt.Sprintf("%g", *val.Float)
	}
	if val.Hex != nil {
		hex := *val.Hex
		switch typeName {
		case "int64", "uint64", "fixed64":
			return hex + "n"
		default:
			return hex
		}
	}
	if val.Int != nil {
		switch typeName {
		case "int64", "uint64", "fixed64":
			return fmt.Sprintf("%dn", *val.Int)
		default:
			return fmt.Sprintf("%d", *val.Int)
		}
	}
	return "undefined"
}
