package consts

import (
	"fmt"
	"strings"
)

// GeneratePython emits Python source code from a parsed .consts.sdl file.
func GeneratePython(cf *ConstFile, opts *GenOpts) ([]byte, error) {
	if opts == nil {
		opts = &GenOpts{}
	}

	var buf strings.Builder

	// Header
	buf.WriteString("# Code generated by forge const -- DO NOT EDIT.\n")
	if opts.SourceName != "" {
		buf.WriteString("#\n")
		buf.WriteString("#   source: " + opts.SourceName + "\n")
	}

	ds := categorize(cf)

	// Self-contained type declarations — Python has no amp tag runtime, so the
	// UID tuple alias and TagName shape are emitted inline.  TagName references
	// UID; uid consts need UID alone.
	if ds.needsTagName() {
		buf.WriteString("\nfrom typing import NamedTuple\n")
	}
	if ds.needsUID() {
		buf.WriteString("\nUID = tuple[int, int]\n")
	}
	if ds.needsTagName() {
		buf.WriteString("\n\nclass TagName(NamedTuple):\n")
		buf.WriteString("    id:      UID\n")
		buf.WriteString("    canonic: str\n")
	}

	for _, tb := range ds.Tags {
		emitPyClass(&buf, tb)
	}

	// Top-level UID consts, then scalar consts — each a module-level run of
	// annotated assignments.
	if len(ds.UIDs) > 0 {
		emitPyConsts(&buf, ds.UIDs)
	}
	if len(ds.Scalars) > 0 {
		emitPyConsts(&buf, ds.Scalars)
	}

	// Grouped constants emit as classes; access is Group.Member.
	for _, grp := range ds.Groups {
		emitPyGroup(&buf, grp)
	}

	return []byte(buf.String()), nil
}

// emitPyClass writes a tags block as a class whose attributes are pre-computed
// TagName records — zero runtime hash cost.
func emitPyClass(buf *strings.Builder, tb *TagsBlock) {
	sections := buildTagSections(tb.Entries)

	// Measure max var name width across all entries for shared column alignment
	maxVar := 0
	for _, sec := range sections {
		for _, entry := range sec.entries {
			if n := len(entry.varName); n > maxVar {
				maxVar = n
			}
		}
	}

	buf.WriteString("\n\nclass " + tb.Name + ":\n")
	for i := range sections {
		if blankBetweenSections(sections, i) {
			buf.WriteString("\n")
		}
		emitPyClassSection(buf, &sections[i], maxVar)
	}
}

// emitPyClassSection writes one alignment group inside a tags class.
func emitPyClassSection(buf *strings.Builder, sec *tagSection, maxVar int) {
	if len(sec.entries) == 0 {
		return
	}

	// Section divider from source comment
	if sec.comment != "" {
		emitSectionHeader(buf, sec.comment, "    # ")
	}

	// First pass: build assignments and measure code column width
	maxCode := 0

	type pyLine struct {
		code   string
		base32 string
	}
	lines := make([]pyLine, len(sec.entries))
	for i, entry := range sec.entries {
		varPad := strings.Repeat(" ", maxVar-len(entry.varName))
		lines[i] = pyLine{
			code:   entry.varName + varPad + " = " + pyTagExpr(&entry),
			base32: entry.base32,
		}
		if n := len(lines[i].code); n > maxCode {
			maxCode = n
		}
	}

	// Second pass: emit aligned entries (canonic is visible in the literal, comment is just Base32)
	for i, entry := range sec.entries {
		line := lines[i]

		// Per-entry doc comment (skip if same text as section header)
		if entry.leadComment != "" && entry.leadComment != sec.comment {
			for _, cl := range strings.Split(entry.leadComment, "\n") {
				buf.WriteString("    # " + cl + "\n")
			}
		}

		codePad := strings.Repeat(" ", maxCode-len(line.code))

		buf.WriteString("    " + line.code + codePad + "  # " + line.base32 + "\n")

		// Visual break after parent entries (children follow)
		if entry.isParent {
			buf.WriteString("\n")
		}
	}
}

// pyTagExpr builds the Python TagName record for a tag entry.
// All entries emit as pre-computed literals.
func pyTagExpr(entry *resolvedEntry) string {
	return fmt.Sprintf("TagName((0x%016X, 0x%016X), %q)", entry.uidHi, entry.uidLo, entry.canonic)
}

// emitPyConsts writes a module-level run of annotated constant assignments with
// an aligned name and type column.  Per-decl doc comments stay inline.
func emitPyConsts(buf *strings.Builder, decls []*ConstDecl) {
	if len(decls) == 0 {
		return
	}

	buf.WriteString("\n\n")

	// Measure name and type widths for alignment
	maxName := 0
	maxType := 0
	for _, decl := range decls {
		if n := len(decl.VarName); n > maxName {
			maxName = n
		}
		if n := len(pyScalarType(decl.Type)); n > maxType {
			maxType = n
		}
	}

	for _, decl := range decls {
		// Individual doc comment
		if decl.LeadComment != "" {
			for _, cl := range strings.Split(decl.LeadComment, "\n") {
				buf.WriteString("# " + cl + "\n")
			}
		}

		pyType := pyScalarType(decl.Type)
		namePad := strings.Repeat(" ", maxName-len(decl.VarName))
		typePad := strings.Repeat(" ", maxType-len(pyType))

		line := decl.VarName + ":" + namePad + " " + pyType + typePad + " = " + pyConstValue(decl.Value)
		if decl.TrailComment != "" {
			line += "  # " + decl.TrailComment
		}
		buf.WriteString(line + "\n")
	}
}

// emitPyGroup writes a const group as a class of annotated attributes.
func emitPyGroup(buf *strings.Builder, grp *ConstGroup) {
	if len(grp.Members) == 0 {
		return
	}

	buf.WriteString("\n\n")
	if grp.LeadComment != "" {
		emitSectionHeader(buf, grp.LeadComment, "# ")
	}

	// Measure member name and type widths for alignment
	maxName := 0
	maxType := 0
	for _, member := range grp.Members {
		if n := len(member.VarName); n > maxName {
			maxName = n
		}
		if n := len(pyScalarType(member.Type)); n > maxType {
			maxType = n
		}
	}

	buf.WriteString("class " + grp.Name + ":\n")
	for _, member := range grp.Members {
		// Per-member doc comment (skip if already used as section header)
		if member.LeadComment != "" && member.LeadComment != grp.LeadComment {
			for _, cl := range strings.Split(member.LeadComment, "\n") {
				buf.WriteString("    # " + cl + "\n")
			}
		}

		pyType := pyScalarType(member.Type)
		namePad := strings.Repeat(" ", maxName-len(member.VarName))
		typePad := strings.Repeat(" ", maxType-len(pyType))

		line := "    " + member.VarName + ":" + namePad + " " + pyType + typePad + " = " + pyConstValue(member.Value)
		if member.TrailComment != "" {
			line += "  # " + member.TrailComment
		}
		buf.WriteString(line + "\n")
	}
}

// pyScalarType maps a .consts.sdl scalar type to its idiomatic Python type.
// Python ints are arbitrary-precision, so every integer width maps to int.
func pyScalarType(typeName string) string {
	switch typeName {
	case "string":
		return "str"
	case "int32", "int64", "uint32", "uint64", "fixed64":
		return "int"
	case "float32", "float", "float64", "double":
		return "float"
	case "uid":
		return "UID"
	default:
		return typeName
	}
}

// pyConstValue formats a Value for Python output.  Python's numeric tower needs
// no per-width formatting, so the value alone determines the literal.
func pyConstValue(val *Value) string {
	if val.UIDPair != nil {
		return fmt.Sprintf("(%s, %s)", val.UIDPair.Hi, val.UIDPair.Lo)
	}
	if val.String != nil {
		return pyQuote(*val.String)
	}
	if val.Float != nil {
		return fmt.Sprintf("%g", *val.Float)
	}
	if val.Hex != nil {
		return *val.Hex
	}
	if val.Int != nil {
		return fmt.Sprintf("%d", *val.Int)
	}
	return "None"
}
