package consts

import (
	"fmt"
	"strconv"
	"strings"
)

// GenerateCSharp emits C# source code from a parsed .consts.sdl file.
func GenerateCSharp(cf *ConstFile, opts *GenOpts) ([]byte, error) {
	if opts == nil {
		opts = &GenOpts{}
	}

	ns := cf.GetOption("csharp_namespace")
	if ns == "" {
		return nil, fmt.Errorf("missing option csharp_namespace")
	}

	var buf strings.Builder

	// Header
	buf.WriteString("// Code generated by forge const -- DO NOT EDIT.\n")
	if opts.SourceName != "" {
		buf.WriteString("//\n")
		buf.WriteString("//   source: " + opts.SourceName + "\n")
	}
	buf.WriteString("\nnamespace " + ns + " {\n")

	// First pass: collect all declarations by category
	var tagsBlocks []*TagsBlock
	var topScalars []*ConstDecl
	var uidConsts []*ConstDecl
	var groups []*ConstGroup
	for _, decl := range cf.Decls {
		switch {
		case decl.Tags != nil:
			tagsBlocks = append(tagsBlocks, decl.Tags)
		case decl.Const != nil:
			if decl.Const.Type == "uid" {
				uidConsts = append(uidConsts, decl.Const)
			} else {
				topScalars = append(topScalars, decl.Const)
			}
		case decl.ConstGrp != nil:
			groups = append(groups, decl.ConstGrp)
		}
	}

	// Emit tags blocks — do NOT fold in top-level UIDs.  Each tags block is a
	// pure tag.Name namespace; UIDs get their own home in the Const class or
	// in whatever ConstGroup they were declared in.
	for _, tb := range tagsBlocks {
		emitCSharpTagsBlock(&buf, tb, "    ")
	}

	// Emit grouped constants (scalars + UIDs coexist as public static readonly).
	for _, grp := range groups {
		emitCSharpConstClass(&buf, grp.Name, grp.Members, grp.LeadComment, "    ")
	}

	// Merge top-level scalars and top-level UIDs into a single "Const" class.
	// No section-header hoist from the first member's comment — per-member
	// doc comments stay inline alongside each field.
	topMembers := append([]*ConstDecl{}, topScalars...)
	topMembers = append(topMembers, uidConsts...)
	if len(topMembers) > 0 {
		emitCSharpConstClass(&buf, "Const", topMembers, "", "    ")
	}

	buf.WriteString("\n}\n")
	return []byte(buf.String()), nil
}

// emitCSharpTagsBlock emits the outer partial class wrapping all tag entries.
// UIDs declared at file scope do NOT fold in here; they belong in their own
// namespace (Const class or their ConstGroup's class).
func emitCSharpTagsBlock(buf *strings.Builder, tb *TagsBlock, indent string) {
	buf.WriteString("\n")
	buf.WriteString(indent + "public static partial class " + tb.Name + " {\n")

	sections := buildTagSections(tb.Entries)
	for _, sec := range sections {
		buf.WriteString("\n")
		emitCSharpTagSection(buf, &sec, indent+"    ")
	}

	buf.WriteString("\n" + indent + "}\n")
}

// emitCSharpTagSection writes one alignment group of C# tag entries.
func emitCSharpTagSection(buf *strings.Builder, sec *tagSection, indent string) {
	if len(sec.entries) == 0 {
		return
	}

	// Section divider
	if sec.comment != "" {
		emitSectionHeader(buf, sec.comment, indent+"// ")
	}

	// Measure column widths
	maxVar := 0
	maxCode := 0

	type csLine struct {
		expr   string // includes trailing ";"
		base32 string
	}

	lines := make([]csLine, len(sec.entries))
	for idx, entry := range sec.entries {
		lines[idx] = csLine{
			expr:   csTagExpr(&entry) + ";",
			base32: entry.base32,
		}
		if n := len(entry.varName); n > maxVar {
			maxVar = n
		}
	}

	for idx, entry := range sec.entries {
		varPad := strings.Repeat(" ", maxVar-len(entry.varName))
		code := "public static readonly TagName " + entry.varName + varPad + " = " + lines[idx].expr
		if n := len(code); n > maxCode {
			maxCode = n
		}
	}

	// Emit aligned entries
	for idx, entry := range sec.entries {
		cl := lines[idx]

		if entry.leadComment != "" && entry.leadComment != sec.comment {
			for _, line := range strings.Split(entry.leadComment, "\n") {
				buf.WriteString(indent + "// " + line + "\n")
			}
		}

		varPad := strings.Repeat(" ", maxVar-len(entry.varName))
		code := "public static readonly TagName " + entry.varName + varPad + " = " + cl.expr
		codePad := strings.Repeat(" ", maxCode-len(code))

		buf.WriteString(indent + code + codePad + "  // " + cl.base32 + "\n")

		if entry.isParent {
			buf.WriteString("\n")
		}
	}
}

// csTagExpr builds the C# TagName expression for a tag entry.
func csTagExpr(entry *resolvedEntry) string {
	return fmt.Sprintf("new(new(0x%016X, 0x%016X), %q)", entry.uidHi, entry.uidLo, entry.canonic)
}

// emitCSharpConstClass writes a partial class of scalar constants.
func emitCSharpConstClass(buf *strings.Builder, className string, decls []*ConstDecl, sectionComment string, indent string) {
	if len(decls) == 0 {
		return
	}

	buf.WriteString("\n")
	if sectionComment != "" {
		emitSectionHeader(buf, sectionComment, indent+"// ")
	}
	buf.WriteString(indent + "public static partial class " + className + " {\n")

	inner := indent + "    "

	// Measure type and var name widths for alignment
	maxType := 0
	maxVar := 0
	for _, member := range decls {
		csType := csharpType(member.Type)
		if n := len(csType); n > maxType {
			maxType = n
		}
		if n := len(member.VarName); n > maxVar {
			maxVar = n
		}
	}

	// Measure full code width for comment alignment
	maxCode := 0
	type constLine struct {
		csType string
		code   string
	}
	lines := make([]constLine, len(decls))
	for idx, member := range decls {
		csType := csharpType(member.Type)
		typePad := strings.Repeat(" ", maxType-len(csType))
		varPad := strings.Repeat(" ", maxVar-len(member.VarName))
		code := "public static readonly " + csType + typePad + " " + member.VarName + varPad + " = " + csharpConstValue(member.Type, member.Value) + ";"
		lines[idx] = constLine{csType: csType, code: code}
		if n := len(code); n > maxCode {
			maxCode = n
		}
	}

	for idx, member := range decls {
		cl := lines[idx]

		// Per-entry doc comment
		if member.LeadComment != "" && member.LeadComment != sectionComment {
			for _, ln := range strings.Split(member.LeadComment, "\n") {
				buf.WriteString(inner + "// " + ln + "\n")
			}
		}

		line := inner + cl.code
		if member.TrailComment != "" {
			codePad := strings.Repeat(" ", maxCode-len(cl.code))
			line += codePad + "  // " + member.TrailComment
		}
		buf.WriteString(line + "\n")
	}

	buf.WriteString(indent + "}\n")
}

func csharpType(typeName string) string {
	switch typeName {
	case "string":
		return "string"
	case "int32":
		return "int"
	case "int64":
		return "long"
	case "uint32":
		return "uint"
	case "uint64", "fixed64":
		return "ulong"
	case "float32", "float":
		return "float"
	case "float64", "double":
		return "double"
	case "uid":
		return "UID"
	default:
		return typeName
	}
}

func csharpConstValue(typeName string, val *Value) string {
	if val.UIDPair != nil {
		return fmt.Sprintf("new(%s, %s)", val.UIDPair.Hi, val.UIDPair.Lo)
	}
	if val.String != nil {
		return strconv.Quote(*val.String)
	}
	if val.Float != nil {
		switch typeName {
		case "float32", "float":
			return fmt.Sprintf("%gf", *val.Float)
		default:
			return fmt.Sprintf("%g", *val.Float)
		}
	}
	if val.Hex != nil {
		hex := *val.Hex
		switch typeName {
		case "uint64", "fixed64":
			return hex + "UL"
		case "uint32":
			return hex + "U"
		case "int64":
			return hex + "L"
		case "float32", "float":
			return hex + "f"
		default:
			return hex
		}
	}
	if val.Int != nil {
		switch typeName {
		case "uint64", "fixed64":
			return fmt.Sprintf("%dUL", *val.Int)
		case "uint32":
			return fmt.Sprintf("%dU", *val.Int)
		case "int64":
			return fmt.Sprintf("%dL", *val.Int)
		case "float32", "float":
			return fmt.Sprintf("%df", *val.Int)
		default:
			return fmt.Sprintf("%d", *val.Int)
		}
	}
	return "null"
}
