package consts

import (
	"fmt"
	"strings"
)

// CEmitter renders C from src
type CEmitter struct{}

func (CEmitter) Generate(src *ConstFile, opts *GenOpts) ([]byte, error) { return GenerateC(src, opts) }
func (CEmitter) Info() EmitterInfo {
	return EmitterInfo{
		Language:  "C",
		Extension: ".h",
		Flag:      "c_out",
	}
}

// GenerateC emits a C99 header from a parsed .consts.sdl file.
//
// C has no namespaces or classes, so each tags block and const group becomes a
// file-scope `static const struct { ... } Name = { ... }` initialized with
// designated initializers — giving the same dotted `Name.Member` access as the
// other targets.  Loose top-level consts fold into a single `Const` struct,
// mirroring the C# emitter.
//
// The UID/TagName types have no amp tag runtime, so they're emitted inline,
// guarded by FORGE_CONSTS_TYPES so several forge headers can be included in one
// translation unit.  64-bit UID halves require <stdint.h>, which is C99 — there
// is no portable pre-C99 64-bit integer type — so the output targets C99.
func GenerateC(src *ConstFile, opts *GenOpts) ([]byte, error) {
	if opts == nil {
		opts = &GenOpts{}
	}

	var buf strings.Builder

	// Header
	buf.WriteString("// Code generated by forge const -- DO NOT EDIT.\n")
	if opts.SourceName != "" {
		buf.WriteString("//\n")
		buf.WriteString("//   source: " + opts.SourceName + "\n")
	}
	buf.WriteString("\n#pragma once\n")

	decls := categorize(src)
	hasBlocks := len(decls.Tags) > 0 || len(decls.Groups) > 0 || len(decls.Scalars) > 0 || len(decls.UIDs) > 0

	// <stdint.h> is needed for UID halves and for any fixed-width integer scalar.
	needStdint := decls.needsUID()
	for _, sc := range decls.Scalars {
		needStdint = needStdint || cNeedsStdint(sc.Type)
	}
	for _, grp := range decls.Groups {
		for _, m := range grp.Members {
			needStdint = needStdint || cNeedsStdint(m.Type)
		}
	}

	if needStdint {
		buf.WriteString("\n#include <stdint.h>\n")
	}

	// Portable "maybe unused" so a header full of constants the including file
	// doesn't all reference stays warning-clean under -Wall -Wextra.
	if hasBlocks {
		buf.WriteString(`
#ifndef FORGE_UNUSED
#if defined(__GNUC__) || defined(__clang__)
#define FORGE_UNUSED __attribute__((unused))
#else
#define FORGE_UNUSED
#endif
#endif
`)
	}

	// Self-contained types, guarded once across all forge headers in a TU.  Both
	// UID and TagName are always defined together so a second header that needs
	// TagName still finds it even if the first only needed UID.
	if decls.needsUID() {
		buf.WriteString(`
#ifndef FORGE_CONSTS_TYPES
#define FORGE_CONSTS_TYPES

typedef struct {
    uint64_t hi;
    uint64_t lo;
} UID;

typedef struct {
    UID         id;
    const char *canonic;
} TagName;

#endif // FORGE_CONSTS_TYPES
`)
	}

	for _, tb := range decls.Tags {
		emitCTagsBlock(&buf, tb)
	}

	// Grouped constants (scalars + UIDs coexist in one struct — C has no const
	// restriction on aggregate members, unlike Go).
	for _, grp := range decls.Groups {
		emitCConstStruct(&buf, grp.Name, grp.Members, grp.LeadComment)
	}

	// Top-level scalars + UIDs fold into a single `Const` struct, mirroring C#.
	topMembers := append([]*ConstDecl{}, decls.Scalars...)
	topMembers = append(topMembers, decls.UIDs...)
	if len(topMembers) > 0 {
		emitCConstStruct(&buf, "Const", topMembers, "")
	}

	return []byte(buf.String()), nil
}

// emitCTagsBlock writes a tags block as a static const struct instance whose
// fields are pre-computed TagName literals — zero runtime hash cost.
func emitCTagsBlock(buf *strings.Builder, tb *TagsBlock) {
	sections := buildTagSections(tb.Entries)

	var all []resolvedEntry
	for _, sec := range sections {
		all = append(all, sec.entries...)
	}

	// Field declarations (all TagName, so no type column to align).
	buf.WriteString("\nstatic const struct {\n")
	for i := range all {
		buf.WriteString("    TagName " + all[i].varName + ";\n")
	}
	buf.WriteString("} " + tb.Name + " FORGE_UNUSED = {\n")

	// Block-global name width so flat sections align together.
	maxName := 0
	for i := range all {
		maxName = max(maxName, len(all[i].varName))
	}

	for i := range sections {
		if blankBetweenSections(sections, i) {
			buf.WriteString("\n")
		}
		emitCTagSection(buf, &sections[i], maxName)
	}

	buf.WriteString("};\n")
}

// emitCTagSection writes one alignment group of designated initializers.
func emitCTagSection(buf *strings.Builder, sec *tagSection, maxName int) {
	if len(sec.entries) == 0 {
		return
	}

	const indent = "    "

	if sec.comment != "" {
		emitSectionHeader(buf, sec.comment, indent+"// ")
	}

	code := func(e *resolvedEntry) string {
		return "." + padRight(e.varName, maxName) + " = " + cTagExpr(e) + ","
	}

	// Measure code width for trailing Base32 alignment.
	maxCode := 0
	for i := range sec.entries {
		maxCode = max(maxCode, len(code(&sec.entries[i])))
	}

	for i := range sec.entries {
		e := &sec.entries[i]

		if e.leadComment != "" && e.leadComment != sec.comment {
			for _, cl := range strings.Split(e.leadComment, "\n") {
				buf.WriteString(indent + "// " + cl + "\n")
			}
		}

		buf.WriteString(indent + padRight(code(e), maxCode) + "  // " + e.base32 + "\n")

		if e.isParent {
			buf.WriteString("\n")
		}
	}
}

// cTagExpr builds the C TagName initializer for a tag entry.
func cTagExpr(entry *resolvedEntry) string {
	return fmt.Sprintf("{ { 0x%016X, 0x%016X }, %s }", entry.uidHi, entry.uidLo, cQuote(entry.canonic))
}

// emitCConstStruct writes a struct instance of scalar / UID constants, used for
// both const groups and the folded top-level `Const` block.
func emitCConstStruct(buf *strings.Builder, name string, members []*ConstDecl, sectionComment string) {
	if len(members) == 0 {
		return
	}

	const indent = "    "

	buf.WriteString("\n")
	if sectionComment != "" {
		emitSectionHeader(buf, sectionComment, "// ")
	}

	// Field declarations: type-first, names aligned to a common column.
	maxPrefix := 0
	for _, m := range members {
		maxPrefix = max(maxPrefix, len(cTypePrefix(m.Type)))
	}
	buf.WriteString("static const struct {\n")
	for _, m := range members {
		buf.WriteString(indent + padRight(cTypePrefix(m.Type), maxPrefix) + m.VarName + ";\n")
	}
	buf.WriteString("} " + name + " FORGE_UNUSED = {\n")

	// Designated initializers, aligned, with optional doc / trailing comments.
	maxName := 0
	for _, m := range members {
		maxName = max(maxName, len(m.VarName))
	}
	code := func(m *ConstDecl) string {
		return "." + padRight(m.VarName, maxName) + " = " + cConstValue(m.Type, m.Value) + ","
	}
	maxCode := 0
	for _, m := range members {
		maxCode = max(maxCode, len(code(m)))
	}

	for _, m := range members {
		if m.LeadComment != "" && m.LeadComment != sectionComment {
			for _, cl := range strings.Split(m.LeadComment, "\n") {
				buf.WriteString(indent + "// " + cl + "\n")
			}
		}

		line := indent + code(m)
		if m.TrailComment != "" {
			line = indent + padRight(code(m), maxCode) + "  // " + m.TrailComment
		}
		buf.WriteString(line + "\n")
	}

	buf.WriteString("};\n")
}

// cTypePrefix is the field-declaration lead for a member type: the C type plus
// the separator before the name.  Pointer types end in `*` so the name hugs it
// (`const char *Name`); value types get a trailing space (`uint64_t Name`).
// padRight then aligns the name column across a struct's members.
func cTypePrefix(typeName string) string {
	ct := cScalarType(typeName)
	if strings.HasSuffix(ct, "*") {
		return ct
	}
	return ct + " "
}

// cScalarType maps a .consts.sdl scalar type to its idiomatic C99 type.
func cScalarType(typeName string) string {
	switch typeName {
	case "string":
		return "const char *"
	case "int32":
		return "int32_t"
	case "int64":
		return "int64_t"
	case "uint32":
		return "uint32_t"
	case "uint64", "fixed64":
		return "uint64_t"
	case "float32", "float":
		return "float"
	case "float64", "double":
		return "double"
	case "uid":
		return "UID"
	default:
		return typeName
	}
}

// cNeedsStdint reports whether a scalar type pulls in <stdint.h>.
func cNeedsStdint(typeName string) bool {
	switch typeName {
	case "int32", "int64", "uint32", "uint64", "fixed64":
		return true
	}
	return false
}

// cConstValue formats a Value for C output.  Integer suffixes use long long
// (LL/ULL) so 64-bit literals are wide enough regardless of platform `long`.
func cConstValue(typeName string, val *Value) string {
	if val.UIDPair != nil {
		return fmt.Sprintf("{ %s, %s }", val.UIDPair.Hi, val.UIDPair.Lo)
	}
	if val.String != nil {
		return cQuote(*val.String)
	}
	if val.Float != nil {
		switch typeName {
		case "float32", "float":
			return fmt.Sprintf("%gf", *val.Float)
		default:
			return fmt.Sprintf("%g", *val.Float)
		}
	}
	if val.Hex != nil {
		hex := *val.Hex
		switch typeName {
		case "uint64", "fixed64":
			return hex + "ULL"
		case "uint32":
			return hex + "U"
		case "int64":
			return hex + "LL"
		default:
			return hex
		}
	}
	if val.Int != nil {
		switch typeName {
		case "uint64", "fixed64":
			return fmt.Sprintf("%dULL", *val.Int)
		case "uint32":
			return fmt.Sprintf("%dU", *val.Int)
		case "int64":
			return fmt.Sprintf("%dLL", *val.Int)
		case "float32", "float":
			return fmt.Sprintf("%df", *val.Int)
		default:
			return fmt.Sprintf("%d", *val.Int)
		}
	}
	return "0"
}
