package consts

import (
	"fmt"
	"path"
	"strconv"
	"strings"
)

// GenerateGo emits Go source code from a parsed .consts.sdl file.
func GenerateGo(cf *ConstFile, opts *GenOpts) ([]byte, error) {
	if opts == nil {
		opts = &GenOpts{}
	}

	goPkg := cf.GetOption("go_package")
	if goPkg == "" {
		return nil, fmt.Errorf("missing option go_package")
	}
	pkgName := path.Base(goPkg)

	var buf strings.Builder

	// Header
	buf.WriteString("// Code generated by forge const -- DO NOT EDIT.\n")
	if opts.SourceName != "" {
		buf.WriteString("//\n")
		buf.WriteString("//   source: " + opts.SourceName + "\n")
	}
	buf.WriteString("\npackage " + pkgName + "\n")

	// Collect declaration categories
	var tagsBlocks []*TagsBlock
	var scalars []*ConstDecl
	var uidConsts []*ConstDecl
	var groups []*ConstGroup
	for _, decl := range cf.Decls {
		switch {
		case decl.Tags != nil:
			tagsBlocks = append(tagsBlocks, decl.Tags)
		case decl.Const != nil:
			if decl.Const.Type == "uid" {
				uidConsts = append(uidConsts, decl.Const)
			} else {
				scalars = append(scalars, decl.Const)
			}
		case decl.ConstGrp != nil:
			groups = append(groups, decl.ConstGrp)
		}
	}

	// Tag name struct + var
	needsTagImport := len(tagsBlocks) > 0 || len(uidConsts) > 0
	if !needsTagImport {
		// Groups may also contain UIDs.
		for _, grp := range groups {
			for _, m := range grp.Members {
				if m.Type == "uid" {
					needsTagImport = true
					break
				}
			}
			if needsTagImport {
				break
			}
		}
	}
	if needsTagImport {
		buf.WriteString("\nimport \"github.com/art-media-platform/amp.SDK/stdlib/tag\"\n")
	}
	for _, tb := range tagsBlocks {
		emitGoTagsStruct(&buf, tb)
	}

	// Top-level UID vars — UIDs can't live in Go const blocks (struct literal),
	// so they emit as package-scope `var` declarations.
	if len(uidConsts) > 0 {
		emitGoVarBlock(&buf, uidConsts, "", "")
	}

	// Top-level scalar constants
	if len(scalars) > 0 {
		emitGoConstBlock(&buf, scalars, "", "")
	}

	// Grouped constants: scalars in const (), UIDs in var () — split per-group,
	// flat-prefixed by group name to match the existing Go-side convention
	// (GlyphWebLink, PlanetInviteFileExt, etc.).
	for _, grp := range groups {
		var grpScalars, grpUIDs []*ConstDecl
		for _, m := range grp.Members {
			if m.Type == "uid" {
				grpUIDs = append(grpUIDs, m)
			} else {
				grpScalars = append(grpScalars, m)
			}
		}
		groupComment := grp.LeadComment
		if len(grpScalars) > 0 {
			emitGoConstBlock(&buf, grpScalars, grp.Name, groupComment)
			groupComment = "" // already consumed as the section header
		}
		if len(grpUIDs) > 0 {
			emitGoVarBlock(&buf, grpUIDs, grp.Name, groupComment)
		}
	}

	return []byte(buf.String()), nil
}

// emitGoTagsStruct writes an anonymous struct var for a tags block.
// All values are pre-computed literals — zero runtime hash cost.
// UIDs declared at file scope do NOT fold in here; they emit as separate
// package-scope vars via emitGoVarBlock so each const lands in its declared
// namespace rather than being jammed into whatever tags block comes first.
func emitGoTagsStruct(buf *strings.Builder, tb *TagsBlock) {
	sections := buildTagSections(tb.Entries)

	// Collect all entries for the struct definition
	var allEntries []resolvedEntry
	for _, sec := range sections {
		allEntries = append(allEntries, sec.entries...)
	}

	// Measure max var name width across all entries
	maxVar := 0
	for _, entry := range allEntries {
		if n := len(entry.varName); n > maxVar {
			maxVar = n
		}
	}

	// Anonymous struct type
	buf.WriteString("\nvar " + tb.Name + " = struct {\n")
	for _, entry := range allEntries {
		pad := strings.Repeat(" ", maxVar-len(entry.varName))
		buf.WriteString("\t" + entry.varName + pad + " tag.Name\n")
	}
	buf.WriteString("}{\n")

	// Initialized values — a blank line sets off grouped sections; runs of flat
	// single entries pack together.
	for i := range sections {
		if blankBetweenSections(sections, i) {
			buf.WriteString("\n")
		}
		emitGoTagSection(buf, &sections[i], maxVar)
	}

	buf.WriteString("}\n")
}

// emitGoTagSection writes one alignment group inside the struct literal.
func emitGoTagSection(buf *strings.Builder, sec *tagSection, maxVar int) {
	if len(sec.entries) == 0 {
		return
	}

	// Section divider from source comment
	if sec.comment != "" {
		emitSectionHeader(buf, sec.comment, "\t// ")
	}

	// First pass: build formatted lines and measure code column width
	maxCode := 0

	type goLine struct {
		code   string
		base32 string
	}
	lines := make([]goLine, len(sec.entries))
	for i, entry := range sec.entries {
		varPad := strings.Repeat(" ", maxVar-len(entry.varName))
		lines[i] = goLine{
			code:   entry.varName + varPad + ": " + goTagExpr(&entry) + ",",
			base32: entry.base32,
		}
		if n := len(lines[i].code); n > maxCode {
			maxCode = n
		}
	}

	// Second pass: emit aligned entries (canonic is visible in the literal, comment is just Base32)
	for i, entry := range sec.entries {
		gl := lines[i]

		// Per-entry doc comment (skip if same text as section header)
		if entry.leadComment != "" && entry.leadComment != sec.comment {
			for _, cl := range strings.Split(entry.leadComment, "\n") {
				buf.WriteString("\t// " + cl + "\n")
			}
		}

		codePad := strings.Repeat(" ", maxCode-len(gl.code))

		trailing := gl.base32

		buf.WriteString("\t" + gl.code + codePad + "  // " + trailing + "\n")

		// Visual break after parent entries (children follow)
		if entry.isParent {
			buf.WriteString("\n")
		}
	}
}

// emitGoVarBlock writes a var () block for declarations that can't live in
// const () — UIDs specifically, since Go forbids struct literals in const.
// Flat-prefixed by groupPrefix when a group name is given, mirroring the
// emitGoConstBlock convention.
func emitGoVarBlock(buf *strings.Builder, decls []*ConstDecl, groupPrefix string, sectionComment string) {
	if len(decls) == 0 {
		return
	}

	buf.WriteString("\n")

	// Section header is emitted ONLY when the caller supplied an explicit group
	// comment.  Same rule as emitGoConstBlock — per-decl comments stay inline.
	if sectionComment != "" {
		emitSectionHeader(buf, sectionComment, "// ")
	}

	// Measure var name widths for alignment
	maxVar := 0
	for _, d := range decls {
		name := groupPrefix + d.VarName
		if n := len(name); n > maxVar {
			maxVar = n
		}
	}

	buf.WriteString("var (\n")
	for _, d := range decls {
		name := groupPrefix + d.VarName

		// Individual doc comment (skip if already used as section header)
		if d.LeadComment != "" && d.LeadComment != sectionComment {
			for _, cl := range strings.Split(d.LeadComment, "\n") {
				buf.WriteString("\t// " + cl + "\n")
			}
		}

		varPad := strings.Repeat(" ", maxVar-len(name))
		val := goConstValue(d.Type, d.Value)

		line := "\t" + name + varPad + " = " + val
		if d.TrailComment != "" {
			line += "  // " + d.TrailComment
		}
		buf.WriteString(line + "\n")
	}
	buf.WriteString(")\n")
}

// goTagExpr builds the Go expression for a tag entry.
// All entries emit as tag.Name with pre-computed literals.
func goTagExpr(entry *resolvedEntry) string {
	return fmt.Sprintf("tag.Name{ID: tag.UID{0x%016X, 0x%016X}, Canonic: %q}", entry.uidHi, entry.uidLo, entry.canonic)
}

// emitGoConstBlock writes a const () block for scalar constants.
func emitGoConstBlock(buf *strings.Builder, decls []*ConstDecl, groupPrefix string, sectionComment string) {
	if len(decls) == 0 {
		return
	}

	buf.WriteString("\n")

	// Section header is emitted ONLY when the caller supplied an explicit group
	// comment (from a `const GroupName { ... }` block).  Per-decl lead comments
	// stay inline — hoisting the first decl's comment to block-header position
	// misleadingly implied it described the whole block.
	if sectionComment != "" {
		emitSectionHeader(buf, sectionComment, "// ")
	}

	// Measure var name widths for alignment
	maxVar := 0
	for _, sc := range decls {
		name := groupPrefix + sc.VarName
		if n := len(name); n > maxVar {
			maxVar = n
		}
	}

	buf.WriteString("const (\n")
	for _, sc := range decls {
		name := groupPrefix + sc.VarName

		// Individual doc comment (skip if already used as section header)
		if sc.LeadComment != "" && sc.LeadComment != sectionComment {
			for _, cl := range strings.Split(sc.LeadComment, "\n") {
				buf.WriteString("\t// " + cl + "\n")
			}
		}

		varPad := strings.Repeat(" ", maxVar-len(name))
		val := goConstValue(sc.Type, sc.Value)

		line := "\t" + name + varPad + " = " + val
		if sc.TrailComment != "" {
			line += "  // " + sc.TrailComment
		}
		buf.WriteString(line + "\n")
	}
	buf.WriteString(")\n")
}

// goConstValue formats a Value for Go const/var output.
func goConstValue(typeName string, val *Value) string {
	if val.UIDPair != nil {
		hi := val.UIDPair.Hi
		lo := val.UIDPair.Lo
		return fmt.Sprintf("tag.UID{%s, %s}", hi, lo)
	}
	if val.String != nil {
		return strconv.Quote(*val.String)
	}
	if val.Float != nil {
		switch typeName {
		case "float32", "float":
			return fmt.Sprintf("float32(%g)", *val.Float)
		default:
			return fmt.Sprintf("%g", *val.Float)
		}
	}
	if val.Hex != nil {
		hex := *val.Hex
		switch typeName {
		case "uint64", "fixed64":
			return fmt.Sprintf("uint64(%s)", hex)
		case "uint32":
			return fmt.Sprintf("uint32(%s)", hex)
		case "int32":
			return fmt.Sprintf("int32(%s)", hex)
		case "float32", "float":
			return fmt.Sprintf("float32(%s)", hex)
		default:
			return hex
		}
	}
	if val.Int != nil {
		switch typeName {
		case "uint64", "fixed64":
			return fmt.Sprintf("uint64(%d)", *val.Int)
		case "uint32":
			return fmt.Sprintf("uint32(%d)", *val.Int)
		case "int32":
			return fmt.Sprintf("int32(%d)", *val.Int)
		case "float32", "float":
			return fmt.Sprintf("float32(%d)", *val.Int)
		default:
			return fmt.Sprintf("%d", *val.Int)
		}
	}
	return "nil"
}
